// Code generated by ent, DO NOT EDIT.

package supplierpayment

import (
	"time"
)

const (
	// Label holds the string label denoting the supplierpayment type in the database.
	Label = "supplier_payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPurchaseInvoiceID holds the string denoting the purchase_invoice_id field in the database.
	FieldPurchaseInvoiceID = "purchase_invoice_id"
	// FieldSupplierID holds the string denoting the supplier_id field in the database.
	FieldSupplierID = "supplier_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPaymentDate holds the string denoting the payment_date field in the database.
	FieldPaymentDate = "payment_date"
	// FieldPaymentMethod holds the string denoting the payment_method field in the database.
	FieldPaymentMethod = "payment_method"
	// FieldReference holds the string denoting the reference field in the database.
	FieldReference = "reference"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the supplierpayment in the database.
	Table = "supplier_payments"
)

// Columns holds all SQL columns for supplierpayment fields.
var Columns = []string{
	FieldID,
	FieldPurchaseInvoiceID,
	FieldSupplierID,
	FieldAmount,
	FieldPaymentDate,
	FieldPaymentMethod,
	FieldReference,
	FieldNotes,
	FieldTenantID,
	FieldUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	AmountValidator func(float64) error
	// DefaultPaymentDate holds the default value on creation for the "payment_date" field.
	DefaultPaymentDate func() time.Time
	// PaymentMethodValidator is a validator for the "payment_method" field. It is called by the builders before save.
	PaymentMethodValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
