// Code generated by ent, DO NOT EDIT.

package supplierpayment

import (
	"Veritasbackend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PurchaseInvoiceID applies equality check predicate on the "purchase_invoice_id" field. It's identical to PurchaseInvoiceIDEQ.
func PurchaseInvoiceID(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// SupplierID applies equality check predicate on the "supplier_id" field. It's identical to SupplierIDEQ.
func SupplierID(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSupplierID), v))
	})
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	})
}

// PaymentDate applies equality check predicate on the "payment_date" field. It's identical to PaymentDateEQ.
func PaymentDate(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentDate), v))
	})
}

// PaymentMethod applies equality check predicate on the "payment_method" field. It's identical to PaymentMethodEQ.
func PaymentMethod(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentMethod), v))
	})
}

// Reference applies equality check predicate on the "reference" field. It's identical to ReferenceEQ.
func Reference(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReference), v))
	})
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNotes), v))
	})
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTenantID), v))
	})
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// PurchaseInvoiceIDEQ applies the EQ predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDNEQ applies the NEQ predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDNEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDIn applies the In predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPurchaseInvoiceID), v...))
	})
}

// PurchaseInvoiceIDNotIn applies the NotIn predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDNotIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPurchaseInvoiceID), v...))
	})
}

// PurchaseInvoiceIDGT applies the GT predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDGT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDGTE applies the GTE predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDGTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDLT applies the LT predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDLT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDLTE applies the LTE predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDLTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPurchaseInvoiceID), v))
	})
}

// SupplierIDEQ applies the EQ predicate on the "supplier_id" field.
func SupplierIDEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSupplierID), v))
	})
}

// SupplierIDNEQ applies the NEQ predicate on the "supplier_id" field.
func SupplierIDNEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSupplierID), v))
	})
}

// SupplierIDIn applies the In predicate on the "supplier_id" field.
func SupplierIDIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSupplierID), v...))
	})
}

// SupplierIDNotIn applies the NotIn predicate on the "supplier_id" field.
func SupplierIDNotIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSupplierID), v...))
	})
}

// SupplierIDGT applies the GT predicate on the "supplier_id" field.
func SupplierIDGT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSupplierID), v))
	})
}

// SupplierIDGTE applies the GTE predicate on the "supplier_id" field.
func SupplierIDGTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSupplierID), v))
	})
}

// SupplierIDLT applies the LT predicate on the "supplier_id" field.
func SupplierIDLT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSupplierID), v))
	})
}

// SupplierIDLTE applies the LTE predicate on the "supplier_id" field.
func SupplierIDLTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSupplierID), v))
	})
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAmount), v))
	})
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAmount), v))
	})
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAmount), v...))
	})
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAmount), v...))
	})
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAmount), v))
	})
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAmount), v))
	})
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAmount), v))
	})
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAmount), v))
	})
}

// PaymentDateEQ applies the EQ predicate on the "payment_date" field.
func PaymentDateEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentDate), v))
	})
}

// PaymentDateNEQ applies the NEQ predicate on the "payment_date" field.
func PaymentDateNEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPaymentDate), v))
	})
}

// PaymentDateIn applies the In predicate on the "payment_date" field.
func PaymentDateIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPaymentDate), v...))
	})
}

// PaymentDateNotIn applies the NotIn predicate on the "payment_date" field.
func PaymentDateNotIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPaymentDate), v...))
	})
}

// PaymentDateGT applies the GT predicate on the "payment_date" field.
func PaymentDateGT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPaymentDate), v))
	})
}

// PaymentDateGTE applies the GTE predicate on the "payment_date" field.
func PaymentDateGTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPaymentDate), v))
	})
}

// PaymentDateLT applies the LT predicate on the "payment_date" field.
func PaymentDateLT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPaymentDate), v))
	})
}

// PaymentDateLTE applies the LTE predicate on the "payment_date" field.
func PaymentDateLTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPaymentDate), v))
	})
}

// PaymentMethodEQ applies the EQ predicate on the "payment_method" field.
func PaymentMethodEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodNEQ applies the NEQ predicate on the "payment_method" field.
func PaymentMethodNEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodIn applies the In predicate on the "payment_method" field.
func PaymentMethodIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPaymentMethod), v...))
	})
}

// PaymentMethodNotIn applies the NotIn predicate on the "payment_method" field.
func PaymentMethodNotIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPaymentMethod), v...))
	})
}

// PaymentMethodGT applies the GT predicate on the "payment_method" field.
func PaymentMethodGT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodGTE applies the GTE predicate on the "payment_method" field.
func PaymentMethodGTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodLT applies the LT predicate on the "payment_method" field.
func PaymentMethodLT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodLTE applies the LTE predicate on the "payment_method" field.
func PaymentMethodLTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodContains applies the Contains predicate on the "payment_method" field.
func PaymentMethodContains(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodHasPrefix applies the HasPrefix predicate on the "payment_method" field.
func PaymentMethodHasPrefix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodHasSuffix applies the HasSuffix predicate on the "payment_method" field.
func PaymentMethodHasSuffix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodEqualFold applies the EqualFold predicate on the "payment_method" field.
func PaymentMethodEqualFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldPaymentMethod), v))
	})
}

// PaymentMethodContainsFold applies the ContainsFold predicate on the "payment_method" field.
func PaymentMethodContainsFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldPaymentMethod), v))
	})
}

// ReferenceEQ applies the EQ predicate on the "reference" field.
func ReferenceEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReference), v))
	})
}

// ReferenceNEQ applies the NEQ predicate on the "reference" field.
func ReferenceNEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReference), v))
	})
}

// ReferenceIn applies the In predicate on the "reference" field.
func ReferenceIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldReference), v...))
	})
}

// ReferenceNotIn applies the NotIn predicate on the "reference" field.
func ReferenceNotIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldReference), v...))
	})
}

// ReferenceGT applies the GT predicate on the "reference" field.
func ReferenceGT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReference), v))
	})
}

// ReferenceGTE applies the GTE predicate on the "reference" field.
func ReferenceGTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReference), v))
	})
}

// ReferenceLT applies the LT predicate on the "reference" field.
func ReferenceLT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReference), v))
	})
}

// ReferenceLTE applies the LTE predicate on the "reference" field.
func ReferenceLTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReference), v))
	})
}

// ReferenceContains applies the Contains predicate on the "reference" field.
func ReferenceContains(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldReference), v))
	})
}

// ReferenceHasPrefix applies the HasPrefix predicate on the "reference" field.
func ReferenceHasPrefix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldReference), v))
	})
}

// ReferenceHasSuffix applies the HasSuffix predicate on the "reference" field.
func ReferenceHasSuffix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldReference), v))
	})
}

// ReferenceIsNil applies the IsNil predicate on the "reference" field.
func ReferenceIsNil() predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldReference)))
	})
}

// ReferenceNotNil applies the NotNil predicate on the "reference" field.
func ReferenceNotNil() predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldReference)))
	})
}

// ReferenceEqualFold applies the EqualFold predicate on the "reference" field.
func ReferenceEqualFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldReference), v))
	})
}

// ReferenceContainsFold applies the ContainsFold predicate on the "reference" field.
func ReferenceContainsFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldReference), v))
	})
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNotes), v))
	})
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNotes), v))
	})
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNotes), v...))
	})
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNotes), v...))
	})
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNotes), v))
	})
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNotes), v))
	})
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNotes), v))
	})
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNotes), v))
	})
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNotes), v))
	})
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNotes), v))
	})
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNotes), v))
	})
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldNotes)))
	})
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldNotes)))
	})
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNotes), v))
	})
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNotes), v))
	})
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTenantID), v))
	})
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTenantID), v))
	})
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTenantID), v...))
	})
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTenantID), v...))
	})
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTenantID), v))
	})
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTenantID), v))
	})
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTenantID), v))
	})
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTenantID), v))
	})
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUserID), v))
	})
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUserID), v))
	})
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUserID), v...))
	})
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUserID), v...))
	})
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUserID), v))
	})
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUserID), v))
	})
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUserID), v))
	})
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUserID), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupplierPayment {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.SupplierPayment(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierPayment) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierPayment) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierPayment) predicate.SupplierPayment {
	return predicate.SupplierPayment(func(s *sql.Selector) {
		p(s.Not())
	})
}
