// Code generated by ent, DO NOT EDIT.

package product

import (
	"time"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldPurchasePrice holds the string denoting the purchase_price field in the database.
	FieldPurchasePrice = "purchase_price"
	// FieldRetailPrice holds the string denoting the retail_price field in the database.
	FieldRetailPrice = "retail_price"
	// FieldWholesalePrice holds the string denoting the wholesale_price field in the database.
	FieldWholesalePrice = "wholesale_price"
	// FieldMinWholesaleQuantity holds the string denoting the min_wholesale_quantity field in the database.
	FieldMinWholesaleQuantity = "min_wholesale_quantity"
	// FieldStock holds the string denoting the stock field in the database.
	FieldStock = "stock"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the product in the database.
	Table = "products"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldPrice,
	FieldPurchasePrice,
	FieldRetailPrice,
	FieldWholesalePrice,
	FieldMinWholesaleQuantity,
	FieldStock,
	FieldSku,
	FieldTenantID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(float64) error
	// DefaultPurchasePrice holds the default value on creation for the "purchase_price" field.
	DefaultPurchasePrice float64
	// PurchasePriceValidator is a validator for the "purchase_price" field. It is called by the builders before save.
	PurchasePriceValidator func(float64) error
	// DefaultRetailPrice holds the default value on creation for the "retail_price" field.
	DefaultRetailPrice float64
	// RetailPriceValidator is a validator for the "retail_price" field. It is called by the builders before save.
	RetailPriceValidator func(float64) error
	// WholesalePriceValidator is a validator for the "wholesale_price" field. It is called by the builders before save.
	WholesalePriceValidator func(float64) error
	// MinWholesaleQuantityValidator is a validator for the "min_wholesale_quantity" field. It is called by the builders before save.
	MinWholesaleQuantityValidator func(int) error
	// DefaultStock holds the default value on creation for the "stock" field.
	DefaultStock int
	// StockValidator is a validator for the "stock" field. It is called by the builders before save.
	StockValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
