// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "total", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "invoice_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[3]},
			},
			{
				Name:    "invoice_user_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[4]},
			},
			{
				Name:    "invoice_status",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[2]},
			},
		},
	}
	// InvoiceItemsColumns holds the columns for the "invoice_items" table.
	InvoiceItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "unit_price", Type: field.TypeFloat64},
		{Name: "subtotal", Type: field.TypeFloat64},
		{Name: "invoice_id", Type: field.TypeInt},
	}
	// InvoiceItemsTable holds the schema information for the "invoice_items" table.
	InvoiceItemsTable = &schema.Table{
		Name:       "invoice_items",
		Columns:    InvoiceItemsColumns,
		PrimaryKey: []*schema.Column{InvoiceItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoice_items_invoices_items",
				Columns:    []*schema.Column{InvoiceItemsColumns[5]},
				RefColumns: []*schema.Column{InvoicesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invoiceitem_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{InvoiceItemsColumns[5]},
			},
			{
				Name:    "invoiceitem_product_id",
				Unique:  false,
				Columns: []*schema.Column{InvoiceItemsColumns[1]},
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "purchase_price", Type: field.TypeFloat64, Default: 0},
		{Name: "retail_price", Type: field.TypeFloat64, Default: 0},
		{Name: "wholesale_price", Type: field.TypeFloat64, Nullable: true},
		{Name: "min_wholesale_quantity", Type: field.TypeInt, Nullable: true},
		{Name: "stock", Type: field.TypeInt, Default: 0},
		{Name: "sku", Type: field.TypeString, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[10]},
			},
			{
				Name:    "product_sku",
				Unique:  false,
				Columns: []*schema.Column{ProductsColumns[9]},
			},
		},
	}
	// PurchaseInvoicesColumns holds the columns for the "purchase_invoices" table.
	PurchaseInvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "invoice_number", Type: field.TypeString},
		{Name: "total", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "payment_method", Type: field.TypeString, Nullable: true},
		{Name: "due_date", Type: field.TypeTime, Nullable: true},
		{Name: "paid_amount", Type: field.TypeFloat64, Default: 0},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "supplier_id", Type: field.TypeInt},
	}
	// PurchaseInvoicesTable holds the schema information for the "purchase_invoices" table.
	PurchaseInvoicesTable = &schema.Table{
		Name:       "purchase_invoices",
		Columns:    PurchaseInvoicesColumns,
		PrimaryKey: []*schema.Column{PurchaseInvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "purchase_invoices_suppliers_supplier",
				Columns:    []*schema.Column{PurchaseInvoicesColumns[11]},
				RefColumns: []*schema.Column{SuppliersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "purchaseinvoice_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoicesColumns[7]},
			},
			{
				Name:    "purchaseinvoice_supplier_id",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoicesColumns[11]},
			},
			{
				Name:    "purchaseinvoice_status",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoicesColumns[3]},
			},
			{
				Name:    "purchaseinvoice_due_date",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoicesColumns[5]},
			},
			{
				Name:    "purchaseinvoice_invoice_number",
				Unique:  true,
				Columns: []*schema.Column{PurchaseInvoicesColumns[1]},
			},
		},
	}
	// PurchaseInvoiceItemsColumns holds the columns for the "purchase_invoice_items" table.
	PurchaseInvoiceItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "purchase_invoice_id", Type: field.TypeInt},
		{Name: "product_id", Type: field.TypeInt},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "unit_cost", Type: field.TypeFloat64},
		{Name: "subtotal", Type: field.TypeFloat64},
	}
	// PurchaseInvoiceItemsTable holds the schema information for the "purchase_invoice_items" table.
	PurchaseInvoiceItemsTable = &schema.Table{
		Name:       "purchase_invoice_items",
		Columns:    PurchaseInvoiceItemsColumns,
		PrimaryKey: []*schema.Column{PurchaseInvoiceItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "purchaseinvoiceitem_purchase_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoiceItemsColumns[1]},
			},
			{
				Name:    "purchaseinvoiceitem_product_id",
				Unique:  false,
				Columns: []*schema.Column{PurchaseInvoiceItemsColumns[2]},
			},
		},
	}
	// SuppliersColumns holds the columns for the "suppliers" table.
	SuppliersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "ruc_nit", Type: field.TypeString, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SuppliersTable holds the schema information for the "suppliers" table.
	SuppliersTable = &schema.Table{
		Name:       "suppliers",
		Columns:    SuppliersColumns,
		PrimaryKey: []*schema.Column{SuppliersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "supplier_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SuppliersColumns[6]},
			},
			{
				Name:    "supplier_ruc_nit",
				Unique:  true,
				Columns: []*schema.Column{SuppliersColumns[5]},
			},
		},
	}
	// SupplierPaymentsColumns holds the columns for the "supplier_payments" table.
	SupplierPaymentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "purchase_invoice_id", Type: field.TypeInt},
		{Name: "supplier_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "payment_date", Type: field.TypeTime},
		{Name: "payment_method", Type: field.TypeString},
		{Name: "reference", Type: field.TypeString, Nullable: true},
		{Name: "notes", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SupplierPaymentsTable holds the schema information for the "supplier_payments" table.
	SupplierPaymentsTable = &schema.Table{
		Name:       "supplier_payments",
		Columns:    SupplierPaymentsColumns,
		PrimaryKey: []*schema.Column{SupplierPaymentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "supplierpayment_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SupplierPaymentsColumns[8]},
			},
			{
				Name:    "supplierpayment_supplier_id",
				Unique:  false,
				Columns: []*schema.Column{SupplierPaymentsColumns[2]},
			},
			{
				Name:    "supplierpayment_purchase_invoice_id",
				Unique:  false,
				Columns: []*schema.Column{SupplierPaymentsColumns[1]},
			},
			{
				Name:    "supplierpayment_payment_date",
				Unique:  false,
				Columns: []*schema.Column{SupplierPaymentsColumns[4]},
			},
		},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "domain", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenant_slug",
				Unique:  true,
				Columns: []*schema.Column{TenantsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
			{
				Name:    "user_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InvoicesTable,
		InvoiceItemsTable,
		ProductsTable,
		PurchaseInvoicesTable,
		PurchaseInvoiceItemsTable,
		SuppliersTable,
		SupplierPaymentsTable,
		TenantsTable,
		UsersTable,
	}
)

func init() {
	InvoiceItemsTable.ForeignKeys[0].RefTable = InvoicesTable
	PurchaseInvoicesTable.ForeignKeys[0].RefTable = SuppliersTable
}
