// Code generated by ent, DO NOT EDIT.

package purchaseinvoiceitem

import (
	"Veritasbackend/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// PurchaseInvoiceID applies equality check predicate on the "purchase_invoice_id" field. It's identical to PurchaseInvoiceIDEQ.
func PurchaseInvoiceID(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProductID), v))
	})
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuantity), v))
	})
}

// UnitCost applies equality check predicate on the "unit_cost" field. It's identical to UnitCostEQ.
func UnitCost(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUnitCost), v))
	})
}

// Subtotal applies equality check predicate on the "subtotal" field. It's identical to SubtotalEQ.
func Subtotal(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSubtotal), v))
	})
}

// PurchaseInvoiceIDEQ applies the EQ predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDNEQ applies the NEQ predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDNEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDIn applies the In predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldPurchaseInvoiceID), v...))
	})
}

// PurchaseInvoiceIDNotIn applies the NotIn predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDNotIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldPurchaseInvoiceID), v...))
	})
}

// PurchaseInvoiceIDGT applies the GT predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDGT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDGTE applies the GTE predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDGTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDLT applies the LT predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDLT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPurchaseInvoiceID), v))
	})
}

// PurchaseInvoiceIDLTE applies the LTE predicate on the "purchase_invoice_id" field.
func PurchaseInvoiceIDLTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPurchaseInvoiceID), v))
	})
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldProductID), v))
	})
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldProductID), v))
	})
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldProductID), v...))
	})
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldProductID), v...))
	})
}

// ProductIDGT applies the GT predicate on the "product_id" field.
func ProductIDGT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldProductID), v))
	})
}

// ProductIDGTE applies the GTE predicate on the "product_id" field.
func ProductIDGTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldProductID), v))
	})
}

// ProductIDLT applies the LT predicate on the "product_id" field.
func ProductIDLT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldProductID), v))
	})
}

// ProductIDLTE applies the LTE predicate on the "product_id" field.
func ProductIDLTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldProductID), v))
	})
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldQuantity), v))
	})
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldQuantity), v))
	})
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldQuantity), v...))
	})
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldQuantity), v...))
	})
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldQuantity), v))
	})
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldQuantity), v))
	})
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldQuantity), v))
	})
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldQuantity), v))
	})
}

// UnitCostEQ applies the EQ predicate on the "unit_cost" field.
func UnitCostEQ(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUnitCost), v))
	})
}

// UnitCostNEQ applies the NEQ predicate on the "unit_cost" field.
func UnitCostNEQ(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUnitCost), v))
	})
}

// UnitCostIn applies the In predicate on the "unit_cost" field.
func UnitCostIn(vs ...float64) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUnitCost), v...))
	})
}

// UnitCostNotIn applies the NotIn predicate on the "unit_cost" field.
func UnitCostNotIn(vs ...float64) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUnitCost), v...))
	})
}

// UnitCostGT applies the GT predicate on the "unit_cost" field.
func UnitCostGT(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUnitCost), v))
	})
}

// UnitCostGTE applies the GTE predicate on the "unit_cost" field.
func UnitCostGTE(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUnitCost), v))
	})
}

// UnitCostLT applies the LT predicate on the "unit_cost" field.
func UnitCostLT(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUnitCost), v))
	})
}

// UnitCostLTE applies the LTE predicate on the "unit_cost" field.
func UnitCostLTE(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUnitCost), v))
	})
}

// SubtotalEQ applies the EQ predicate on the "subtotal" field.
func SubtotalEQ(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSubtotal), v))
	})
}

// SubtotalNEQ applies the NEQ predicate on the "subtotal" field.
func SubtotalNEQ(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSubtotal), v))
	})
}

// SubtotalIn applies the In predicate on the "subtotal" field.
func SubtotalIn(vs ...float64) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSubtotal), v...))
	})
}

// SubtotalNotIn applies the NotIn predicate on the "subtotal" field.
func SubtotalNotIn(vs ...float64) predicate.PurchaseInvoiceItem {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSubtotal), v...))
	})
}

// SubtotalGT applies the GT predicate on the "subtotal" field.
func SubtotalGT(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSubtotal), v))
	})
}

// SubtotalGTE applies the GTE predicate on the "subtotal" field.
func SubtotalGTE(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSubtotal), v))
	})
}

// SubtotalLT applies the LT predicate on the "subtotal" field.
func SubtotalLT(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSubtotal), v))
	})
}

// SubtotalLTE applies the LTE predicate on the "subtotal" field.
func SubtotalLTE(v float64) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSubtotal), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PurchaseInvoiceItem) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PurchaseInvoiceItem) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PurchaseInvoiceItem) predicate.PurchaseInvoiceItem {
	return predicate.PurchaseInvoiceItem(func(s *sql.Selector) {
		p(s.Not())
	})
}
