// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/invoice"
	"Veritasbackend/ent/invoiceitem"
	"Veritasbackend/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvoiceItemUpdate is the builder for updating InvoiceItem entities.
type InvoiceItemUpdate struct {
	config
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Where appends a list predicates to the InvoiceItemUpdate builder.
func (iiu *InvoiceItemUpdate) Where(ps ...predicate.InvoiceItem) *InvoiceItemUpdate {
	iiu.mutation.Where(ps...)
	return iiu
}

// SetInvoiceID sets the "invoice_id" field.
func (iiu *InvoiceItemUpdate) SetInvoiceID(i int) *InvoiceItemUpdate {
	iiu.mutation.SetInvoiceID(i)
	return iiu
}

// SetProductID sets the "product_id" field.
func (iiu *InvoiceItemUpdate) SetProductID(i int) *InvoiceItemUpdate {
	iiu.mutation.ResetProductID()
	iiu.mutation.SetProductID(i)
	return iiu
}

// AddProductID adds i to the "product_id" field.
func (iiu *InvoiceItemUpdate) AddProductID(i int) *InvoiceItemUpdate {
	iiu.mutation.AddProductID(i)
	return iiu
}

// SetQuantity sets the "quantity" field.
func (iiu *InvoiceItemUpdate) SetQuantity(i int) *InvoiceItemUpdate {
	iiu.mutation.ResetQuantity()
	iiu.mutation.SetQuantity(i)
	return iiu
}

// AddQuantity adds i to the "quantity" field.
func (iiu *InvoiceItemUpdate) AddQuantity(i int) *InvoiceItemUpdate {
	iiu.mutation.AddQuantity(i)
	return iiu
}

// SetUnitPrice sets the "unit_price" field.
func (iiu *InvoiceItemUpdate) SetUnitPrice(f float64) *InvoiceItemUpdate {
	iiu.mutation.ResetUnitPrice()
	iiu.mutation.SetUnitPrice(f)
	return iiu
}

// AddUnitPrice adds f to the "unit_price" field.
func (iiu *InvoiceItemUpdate) AddUnitPrice(f float64) *InvoiceItemUpdate {
	iiu.mutation.AddUnitPrice(f)
	return iiu
}

// SetSubtotal sets the "subtotal" field.
func (iiu *InvoiceItemUpdate) SetSubtotal(f float64) *InvoiceItemUpdate {
	iiu.mutation.ResetSubtotal()
	iiu.mutation.SetSubtotal(f)
	return iiu
}

// AddSubtotal adds f to the "subtotal" field.
func (iiu *InvoiceItemUpdate) AddSubtotal(f float64) *InvoiceItemUpdate {
	iiu.mutation.AddSubtotal(f)
	return iiu
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (iiu *InvoiceItemUpdate) SetInvoice(i *Invoice) *InvoiceItemUpdate {
	return iiu.SetInvoiceID(i.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (iiu *InvoiceItemUpdate) Mutation() *InvoiceItemMutation {
	return iiu.mutation
}

// ClearInvoice clears the "invoice" edge to the Invoice entity.
func (iiu *InvoiceItemUpdate) ClearInvoice() *InvoiceItemUpdate {
	iiu.mutation.ClearInvoice()
	return iiu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iiu *InvoiceItemUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iiu.hooks) == 0 {
		if err = iiu.check(); err != nil {
			return 0, err
		}
		affected, err = iiu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvoiceItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = iiu.check(); err != nil {
				return 0, err
			}
			iiu.mutation = mutation
			affected, err = iiu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iiu.hooks) - 1; i >= 0; i-- {
			if iiu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iiu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iiu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (iiu *InvoiceItemUpdate) SaveX(ctx context.Context) int {
	affected, err := iiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iiu *InvoiceItemUpdate) Exec(ctx context.Context) error {
	_, err := iiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iiu *InvoiceItemUpdate) ExecX(ctx context.Context) {
	if err := iiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iiu *InvoiceItemUpdate) check() error {
	if v, ok := iiu.mutation.Quantity(); ok {
		if err := invoiceitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.quantity": %w`, err)}
		}
	}
	if v, ok := iiu.mutation.UnitPrice(); ok {
		if err := invoiceitem.UnitPriceValidator(v); err != nil {
			return &ValidationError{Name: "unit_price", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.unit_price": %w`, err)}
		}
	}
	if v, ok := iiu.mutation.Subtotal(); ok {
		if err := invoiceitem.SubtotalValidator(v); err != nil {
			return &ValidationError{Name: "subtotal", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.subtotal": %w`, err)}
		}
	}
	if _, ok := iiu.mutation.InvoiceID(); iiu.mutation.InvoiceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "InvoiceItem.invoice"`)
	}
	return nil
}

func (iiu *InvoiceItemUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   invoiceitem.Table,
			Columns: invoiceitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: invoiceitem.FieldID,
			},
		},
	}
	if ps := iiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iiu.mutation.ProductID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldProductID,
		})
	}
	if value, ok := iiu.mutation.AddedProductID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldProductID,
		})
	}
	if value, ok := iiu.mutation.Quantity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldQuantity,
		})
	}
	if value, ok := iiu.mutation.AddedQuantity(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldQuantity,
		})
	}
	if value, ok := iiu.mutation.UnitPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldUnitPrice,
		})
	}
	if value, ok := iiu.mutation.AddedUnitPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldUnitPrice,
		})
	}
	if value, ok := iiu.mutation.Subtotal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldSubtotal,
		})
	}
	if value, ok := iiu.mutation.AddedSubtotal(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldSubtotal,
		})
	}
	if iiu.mutation.InvoiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: invoice.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iiu.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: invoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// InvoiceItemUpdateOne is the builder for updating a single InvoiceItem entity.
type InvoiceItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// SetInvoiceID sets the "invoice_id" field.
func (iiuo *InvoiceItemUpdateOne) SetInvoiceID(i int) *InvoiceItemUpdateOne {
	iiuo.mutation.SetInvoiceID(i)
	return iiuo
}

// SetProductID sets the "product_id" field.
func (iiuo *InvoiceItemUpdateOne) SetProductID(i int) *InvoiceItemUpdateOne {
	iiuo.mutation.ResetProductID()
	iiuo.mutation.SetProductID(i)
	return iiuo
}

// AddProductID adds i to the "product_id" field.
func (iiuo *InvoiceItemUpdateOne) AddProductID(i int) *InvoiceItemUpdateOne {
	iiuo.mutation.AddProductID(i)
	return iiuo
}

// SetQuantity sets the "quantity" field.
func (iiuo *InvoiceItemUpdateOne) SetQuantity(i int) *InvoiceItemUpdateOne {
	iiuo.mutation.ResetQuantity()
	iiuo.mutation.SetQuantity(i)
	return iiuo
}

// AddQuantity adds i to the "quantity" field.
func (iiuo *InvoiceItemUpdateOne) AddQuantity(i int) *InvoiceItemUpdateOne {
	iiuo.mutation.AddQuantity(i)
	return iiuo
}

// SetUnitPrice sets the "unit_price" field.
func (iiuo *InvoiceItemUpdateOne) SetUnitPrice(f float64) *InvoiceItemUpdateOne {
	iiuo.mutation.ResetUnitPrice()
	iiuo.mutation.SetUnitPrice(f)
	return iiuo
}

// AddUnitPrice adds f to the "unit_price" field.
func (iiuo *InvoiceItemUpdateOne) AddUnitPrice(f float64) *InvoiceItemUpdateOne {
	iiuo.mutation.AddUnitPrice(f)
	return iiuo
}

// SetSubtotal sets the "subtotal" field.
func (iiuo *InvoiceItemUpdateOne) SetSubtotal(f float64) *InvoiceItemUpdateOne {
	iiuo.mutation.ResetSubtotal()
	iiuo.mutation.SetSubtotal(f)
	return iiuo
}

// AddSubtotal adds f to the "subtotal" field.
func (iiuo *InvoiceItemUpdateOne) AddSubtotal(f float64) *InvoiceItemUpdateOne {
	iiuo.mutation.AddSubtotal(f)
	return iiuo
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (iiuo *InvoiceItemUpdateOne) SetInvoice(i *Invoice) *InvoiceItemUpdateOne {
	return iiuo.SetInvoiceID(i.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (iiuo *InvoiceItemUpdateOne) Mutation() *InvoiceItemMutation {
	return iiuo.mutation
}

// ClearInvoice clears the "invoice" edge to the Invoice entity.
func (iiuo *InvoiceItemUpdateOne) ClearInvoice() *InvoiceItemUpdateOne {
	iiuo.mutation.ClearInvoice()
	return iiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iiuo *InvoiceItemUpdateOne) Select(field string, fields ...string) *InvoiceItemUpdateOne {
	iiuo.fields = append([]string{field}, fields...)
	return iiuo
}

// Save executes the query and returns the updated InvoiceItem entity.
func (iiuo *InvoiceItemUpdateOne) Save(ctx context.Context) (*InvoiceItem, error) {
	var (
		err  error
		node *InvoiceItem
	)
	if len(iiuo.hooks) == 0 {
		if err = iiuo.check(); err != nil {
			return nil, err
		}
		node, err = iiuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvoiceItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = iiuo.check(); err != nil {
				return nil, err
			}
			iiuo.mutation = mutation
			node, err = iiuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(iiuo.hooks) - 1; i >= 0; i-- {
			if iiuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iiuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, iiuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*InvoiceItem)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from InvoiceItemMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (iiuo *InvoiceItemUpdateOne) SaveX(ctx context.Context) *InvoiceItem {
	node, err := iiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iiuo *InvoiceItemUpdateOne) Exec(ctx context.Context) error {
	_, err := iiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iiuo *InvoiceItemUpdateOne) ExecX(ctx context.Context) {
	if err := iiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iiuo *InvoiceItemUpdateOne) check() error {
	if v, ok := iiuo.mutation.Quantity(); ok {
		if err := invoiceitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.quantity": %w`, err)}
		}
	}
	if v, ok := iiuo.mutation.UnitPrice(); ok {
		if err := invoiceitem.UnitPriceValidator(v); err != nil {
			return &ValidationError{Name: "unit_price", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.unit_price": %w`, err)}
		}
	}
	if v, ok := iiuo.mutation.Subtotal(); ok {
		if err := invoiceitem.SubtotalValidator(v); err != nil {
			return &ValidationError{Name: "subtotal", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.subtotal": %w`, err)}
		}
	}
	if _, ok := iiuo.mutation.InvoiceID(); iiuo.mutation.InvoiceCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "InvoiceItem.invoice"`)
	}
	return nil
}

func (iiuo *InvoiceItemUpdateOne) sqlSave(ctx context.Context) (_node *InvoiceItem, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   invoiceitem.Table,
			Columns: invoiceitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: invoiceitem.FieldID,
			},
		},
	}
	id, ok := iiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InvoiceItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoiceitem.FieldID)
		for _, f := range fields {
			if !invoiceitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invoiceitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iiuo.mutation.ProductID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldProductID,
		})
	}
	if value, ok := iiuo.mutation.AddedProductID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldProductID,
		})
	}
	if value, ok := iiuo.mutation.Quantity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldQuantity,
		})
	}
	if value, ok := iiuo.mutation.AddedQuantity(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldQuantity,
		})
	}
	if value, ok := iiuo.mutation.UnitPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldUnitPrice,
		})
	}
	if value, ok := iiuo.mutation.AddedUnitPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldUnitPrice,
		})
	}
	if value, ok := iiuo.mutation.Subtotal(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldSubtotal,
		})
	}
	if value, ok := iiuo.mutation.AddedSubtotal(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldSubtotal,
		})
	}
	if iiuo.mutation.InvoiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: invoice.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iiuo.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: invoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &InvoiceItem{config: iiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoiceitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
