// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/invoice"
	"Veritasbackend/ent/invoiceitem"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvoiceItemCreate is the builder for creating a InvoiceItem entity.
type InvoiceItemCreate struct {
	config
	mutation *InvoiceItemMutation
	hooks    []Hook
}

// SetInvoiceID sets the "invoice_id" field.
func (iic *InvoiceItemCreate) SetInvoiceID(i int) *InvoiceItemCreate {
	iic.mutation.SetInvoiceID(i)
	return iic
}

// SetProductID sets the "product_id" field.
func (iic *InvoiceItemCreate) SetProductID(i int) *InvoiceItemCreate {
	iic.mutation.SetProductID(i)
	return iic
}

// SetQuantity sets the "quantity" field.
func (iic *InvoiceItemCreate) SetQuantity(i int) *InvoiceItemCreate {
	iic.mutation.SetQuantity(i)
	return iic
}

// SetUnitPrice sets the "unit_price" field.
func (iic *InvoiceItemCreate) SetUnitPrice(f float64) *InvoiceItemCreate {
	iic.mutation.SetUnitPrice(f)
	return iic
}

// SetSubtotal sets the "subtotal" field.
func (iic *InvoiceItemCreate) SetSubtotal(f float64) *InvoiceItemCreate {
	iic.mutation.SetSubtotal(f)
	return iic
}

// SetInvoice sets the "invoice" edge to the Invoice entity.
func (iic *InvoiceItemCreate) SetInvoice(i *Invoice) *InvoiceItemCreate {
	return iic.SetInvoiceID(i.ID)
}

// Mutation returns the InvoiceItemMutation object of the builder.
func (iic *InvoiceItemCreate) Mutation() *InvoiceItemMutation {
	return iic.mutation
}

// Save creates the InvoiceItem in the database.
func (iic *InvoiceItemCreate) Save(ctx context.Context) (*InvoiceItem, error) {
	var (
		err  error
		node *InvoiceItem
	)
	if len(iic.hooks) == 0 {
		if err = iic.check(); err != nil {
			return nil, err
		}
		node, err = iic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvoiceItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = iic.check(); err != nil {
				return nil, err
			}
			iic.mutation = mutation
			if node, err = iic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(iic.hooks) - 1; i >= 0; i-- {
			if iic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, iic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*InvoiceItem)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from InvoiceItemMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (iic *InvoiceItemCreate) SaveX(ctx context.Context) *InvoiceItem {
	v, err := iic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iic *InvoiceItemCreate) Exec(ctx context.Context) error {
	_, err := iic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iic *InvoiceItemCreate) ExecX(ctx context.Context) {
	if err := iic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iic *InvoiceItemCreate) check() error {
	if _, ok := iic.mutation.InvoiceID(); !ok {
		return &ValidationError{Name: "invoice_id", err: errors.New(`ent: missing required field "InvoiceItem.invoice_id"`)}
	}
	if _, ok := iic.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "InvoiceItem.product_id"`)}
	}
	if _, ok := iic.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "InvoiceItem.quantity"`)}
	}
	if v, ok := iic.mutation.Quantity(); ok {
		if err := invoiceitem.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.quantity": %w`, err)}
		}
	}
	if _, ok := iic.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "InvoiceItem.unit_price"`)}
	}
	if v, ok := iic.mutation.UnitPrice(); ok {
		if err := invoiceitem.UnitPriceValidator(v); err != nil {
			return &ValidationError{Name: "unit_price", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.unit_price": %w`, err)}
		}
	}
	if _, ok := iic.mutation.Subtotal(); !ok {
		return &ValidationError{Name: "subtotal", err: errors.New(`ent: missing required field "InvoiceItem.subtotal"`)}
	}
	if v, ok := iic.mutation.Subtotal(); ok {
		if err := invoiceitem.SubtotalValidator(v); err != nil {
			return &ValidationError{Name: "subtotal", err: fmt.Errorf(`ent: validator failed for field "InvoiceItem.subtotal": %w`, err)}
		}
	}
	if _, ok := iic.mutation.InvoiceID(); !ok {
		return &ValidationError{Name: "invoice", err: errors.New(`ent: missing required edge "InvoiceItem.invoice"`)}
	}
	return nil
}

func (iic *InvoiceItemCreate) sqlSave(ctx context.Context) (*InvoiceItem, error) {
	_node, _spec := iic.createSpec()
	if err := sqlgraph.CreateNode(ctx, iic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (iic *InvoiceItemCreate) createSpec() (*InvoiceItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InvoiceItem{config: iic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: invoiceitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: invoiceitem.FieldID,
			},
		}
	)
	if value, ok := iic.mutation.ProductID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldProductID,
		})
		_node.ProductID = value
	}
	if value, ok := iic.mutation.Quantity(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: invoiceitem.FieldQuantity,
		})
		_node.Quantity = value
	}
	if value, ok := iic.mutation.UnitPrice(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldUnitPrice,
		})
		_node.UnitPrice = value
	}
	if value, ok := iic.mutation.Subtotal(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: invoiceitem.FieldSubtotal,
		})
		_node.Subtotal = value
	}
	if nodes := iic.mutation.InvoiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoiceitem.InvoiceTable,
			Columns: []string{invoiceitem.InvoiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: invoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvoiceItemCreateBulk is the builder for creating many InvoiceItem entities in bulk.
type InvoiceItemCreateBulk struct {
	config
	builders []*InvoiceItemCreate
}

// Save creates the InvoiceItem entities in the database.
func (iicb *InvoiceItemCreateBulk) Save(ctx context.Context) ([]*InvoiceItem, error) {
	specs := make([]*sqlgraph.CreateSpec, len(iicb.builders))
	nodes := make([]*InvoiceItem, len(iicb.builders))
	mutators := make([]Mutator, len(iicb.builders))
	for i := range iicb.builders {
		func(i int, root context.Context) {
			builder := iicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, iicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, iicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, iicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (iicb *InvoiceItemCreateBulk) SaveX(ctx context.Context) []*InvoiceItem {
	v, err := iicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (iicb *InvoiceItemCreateBulk) Exec(ctx context.Context) error {
	_, err := iicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iicb *InvoiceItemCreateBulk) ExecX(ctx context.Context) {
	if err := iicb.Exec(ctx); err != nil {
		panic(err)
	}
}
