// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/invoiceitem"
	"Veritasbackend/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvoiceItemDelete is the builder for deleting a InvoiceItem entity.
type InvoiceItemDelete struct {
	config
	hooks    []Hook
	mutation *InvoiceItemMutation
}

// Where appends a list predicates to the InvoiceItemDelete builder.
func (iid *InvoiceItemDelete) Where(ps ...predicate.InvoiceItem) *InvoiceItemDelete {
	iid.mutation.Where(ps...)
	return iid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iid *InvoiceItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iid.hooks) == 0 {
		affected, err = iid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvoiceItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iid.mutation = mutation
			affected, err = iid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iid.hooks) - 1; i >= 0; i-- {
			if iid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (iid *InvoiceItemDelete) ExecX(ctx context.Context) int {
	n, err := iid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iid *InvoiceItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: invoiceitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: invoiceitem.FieldID,
			},
		},
	}
	if ps := iid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, iid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// InvoiceItemDeleteOne is the builder for deleting a single InvoiceItem entity.
type InvoiceItemDeleteOne struct {
	iid *InvoiceItemDelete
}

// Exec executes the deletion query.
func (iido *InvoiceItemDeleteOne) Exec(ctx context.Context) error {
	n, err := iido.iid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invoiceitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iido *InvoiceItemDeleteOne) ExecX(ctx context.Context) {
	iido.iid.ExecX(ctx)
}
