// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/predicate"
	"Veritasbackend/ent/product"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks    []Hook
	mutation *ProductMutation
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *ProductUpdate) SetName(s string) *ProductUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProductUpdate) SetDescription(s string) *ProductUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDescription(s *string) *ProductUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// ClearDescription clears the value of the "description" field.
func (pu *ProductUpdate) ClearDescription() *ProductUpdate {
	pu.mutation.ClearDescription()
	return pu
}

// SetPrice sets the "price" field.
func (pu *ProductUpdate) SetPrice(f float64) *ProductUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(f)
	return pu
}

// AddPrice adds f to the "price" field.
func (pu *ProductUpdate) AddPrice(f float64) *ProductUpdate {
	pu.mutation.AddPrice(f)
	return pu
}

// SetPurchasePrice sets the "purchase_price" field.
func (pu *ProductUpdate) SetPurchasePrice(f float64) *ProductUpdate {
	pu.mutation.ResetPurchasePrice()
	pu.mutation.SetPurchasePrice(f)
	return pu
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillablePurchasePrice(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetPurchasePrice(*f)
	}
	return pu
}

// AddPurchasePrice adds f to the "purchase_price" field.
func (pu *ProductUpdate) AddPurchasePrice(f float64) *ProductUpdate {
	pu.mutation.AddPurchasePrice(f)
	return pu
}

// SetRetailPrice sets the "retail_price" field.
func (pu *ProductUpdate) SetRetailPrice(f float64) *ProductUpdate {
	pu.mutation.ResetRetailPrice()
	pu.mutation.SetRetailPrice(f)
	return pu
}

// SetNillableRetailPrice sets the "retail_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableRetailPrice(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetRetailPrice(*f)
	}
	return pu
}

// AddRetailPrice adds f to the "retail_price" field.
func (pu *ProductUpdate) AddRetailPrice(f float64) *ProductUpdate {
	pu.mutation.AddRetailPrice(f)
	return pu
}

// SetWholesalePrice sets the "wholesale_price" field.
func (pu *ProductUpdate) SetWholesalePrice(f float64) *ProductUpdate {
	pu.mutation.ResetWholesalePrice()
	pu.mutation.SetWholesalePrice(f)
	return pu
}

// SetNillableWholesalePrice sets the "wholesale_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableWholesalePrice(f *float64) *ProductUpdate {
	if f != nil {
		pu.SetWholesalePrice(*f)
	}
	return pu
}

// AddWholesalePrice adds f to the "wholesale_price" field.
func (pu *ProductUpdate) AddWholesalePrice(f float64) *ProductUpdate {
	pu.mutation.AddWholesalePrice(f)
	return pu
}

// ClearWholesalePrice clears the value of the "wholesale_price" field.
func (pu *ProductUpdate) ClearWholesalePrice() *ProductUpdate {
	pu.mutation.ClearWholesalePrice()
	return pu
}

// SetMinWholesaleQuantity sets the "min_wholesale_quantity" field.
func (pu *ProductUpdate) SetMinWholesaleQuantity(i int) *ProductUpdate {
	pu.mutation.ResetMinWholesaleQuantity()
	pu.mutation.SetMinWholesaleQuantity(i)
	return pu
}

// SetNillableMinWholesaleQuantity sets the "min_wholesale_quantity" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableMinWholesaleQuantity(i *int) *ProductUpdate {
	if i != nil {
		pu.SetMinWholesaleQuantity(*i)
	}
	return pu
}

// AddMinWholesaleQuantity adds i to the "min_wholesale_quantity" field.
func (pu *ProductUpdate) AddMinWholesaleQuantity(i int) *ProductUpdate {
	pu.mutation.AddMinWholesaleQuantity(i)
	return pu
}

// ClearMinWholesaleQuantity clears the value of the "min_wholesale_quantity" field.
func (pu *ProductUpdate) ClearMinWholesaleQuantity() *ProductUpdate {
	pu.mutation.ClearMinWholesaleQuantity()
	return pu
}

// SetStock sets the "stock" field.
func (pu *ProductUpdate) SetStock(i int) *ProductUpdate {
	pu.mutation.ResetStock()
	pu.mutation.SetStock(i)
	return pu
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableStock(i *int) *ProductUpdate {
	if i != nil {
		pu.SetStock(*i)
	}
	return pu
}

// AddStock adds i to the "stock" field.
func (pu *ProductUpdate) AddStock(i int) *ProductUpdate {
	pu.mutation.AddStock(i)
	return pu
}

// SetSku sets the "sku" field.
func (pu *ProductUpdate) SetSku(s string) *ProductUpdate {
	pu.mutation.SetSku(s)
	return pu
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableSku(s *string) *ProductUpdate {
	if s != nil {
		pu.SetSku(*s)
	}
	return pu
}

// ClearSku clears the value of the "sku" field.
func (pu *ProductUpdate) ClearSku() *ProductUpdate {
	pu.mutation.ClearSku()
	return pu
}

// SetTenantID sets the "tenant_id" field.
func (pu *ProductUpdate) SetTenantID(i int) *ProductUpdate {
	pu.mutation.ResetTenantID()
	pu.mutation.SetTenantID(i)
	return pu
}

// AddTenantID adds i to the "tenant_id" field.
func (pu *ProductUpdate) AddTenantID(i int) *ProductUpdate {
	pu.mutation.AddTenantID(i)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProductUpdate) SetUpdatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	pu.defaults()
	if len(pu.hooks) == 0 {
		if err = pu.check(); err != nil {
			return 0, err
		}
		affected, err = pu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pu.check(); err != nil {
				return 0, err
			}
			pu.mutation = mutation
			affected, err = pu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pu.hooks) - 1; i >= 0; i-- {
			if pu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProductUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := product.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProductUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Price(); ok {
		if err := product.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Product.price": %w`, err)}
		}
	}
	if v, ok := pu.mutation.PurchasePrice(); ok {
		if err := product.PurchasePriceValidator(v); err != nil {
			return &ValidationError{Name: "purchase_price", err: fmt.Errorf(`ent: validator failed for field "Product.purchase_price": %w`, err)}
		}
	}
	if v, ok := pu.mutation.RetailPrice(); ok {
		if err := product.RetailPriceValidator(v); err != nil {
			return &ValidationError{Name: "retail_price", err: fmt.Errorf(`ent: validator failed for field "Product.retail_price": %w`, err)}
		}
	}
	if v, ok := pu.mutation.WholesalePrice(); ok {
		if err := product.WholesalePriceValidator(v); err != nil {
			return &ValidationError{Name: "wholesale_price", err: fmt.Errorf(`ent: validator failed for field "Product.wholesale_price": %w`, err)}
		}
	}
	if v, ok := pu.mutation.MinWholesaleQuantity(); ok {
		if err := product.MinWholesaleQuantityValidator(v); err != nil {
			return &ValidationError{Name: "min_wholesale_quantity", err: fmt.Errorf(`ent: validator failed for field "Product.min_wholesale_quantity": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Stock(); ok {
		if err := product.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "Product.stock": %w`, err)}
		}
	}
	return nil
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   product.Table,
			Columns: product.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: product.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldName,
		})
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldDescription,
		})
	}
	if pu.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: product.FieldDescription,
		})
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPrice,
		})
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPrice,
		})
	}
	if value, ok := pu.mutation.PurchasePrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPurchasePrice,
		})
	}
	if value, ok := pu.mutation.AddedPurchasePrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPurchasePrice,
		})
	}
	if value, ok := pu.mutation.RetailPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldRetailPrice,
		})
	}
	if value, ok := pu.mutation.AddedRetailPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldRetailPrice,
		})
	}
	if value, ok := pu.mutation.WholesalePrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldWholesalePrice,
		})
	}
	if value, ok := pu.mutation.AddedWholesalePrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldWholesalePrice,
		})
	}
	if pu.mutation.WholesalePriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: product.FieldWholesalePrice,
		})
	}
	if value, ok := pu.mutation.MinWholesaleQuantity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if value, ok := pu.mutation.AddedMinWholesaleQuantity(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if pu.mutation.MinWholesaleQuantityCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if value, ok := pu.mutation.Stock(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldStock,
		})
	}
	if value, ok := pu.mutation.AddedStock(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldStock,
		})
	}
	if value, ok := pu.mutation.Sku(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldSku,
		})
	}
	if pu.mutation.SkuCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: product.FieldSku,
		})
	}
	if value, ok := pu.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldTenantID,
		})
	}
	if value, ok := pu.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldTenantID,
		})
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: product.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductMutation
}

// SetName sets the "name" field.
func (puo *ProductUpdateOne) SetName(s string) *ProductUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProductUpdateOne) SetDescription(s string) *ProductUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDescription(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// ClearDescription clears the value of the "description" field.
func (puo *ProductUpdateOne) ClearDescription() *ProductUpdateOne {
	puo.mutation.ClearDescription()
	return puo
}

// SetPrice sets the "price" field.
func (puo *ProductUpdateOne) SetPrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(f)
	return puo
}

// AddPrice adds f to the "price" field.
func (puo *ProductUpdateOne) AddPrice(f float64) *ProductUpdateOne {
	puo.mutation.AddPrice(f)
	return puo
}

// SetPurchasePrice sets the "purchase_price" field.
func (puo *ProductUpdateOne) SetPurchasePrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetPurchasePrice()
	puo.mutation.SetPurchasePrice(f)
	return puo
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillablePurchasePrice(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetPurchasePrice(*f)
	}
	return puo
}

// AddPurchasePrice adds f to the "purchase_price" field.
func (puo *ProductUpdateOne) AddPurchasePrice(f float64) *ProductUpdateOne {
	puo.mutation.AddPurchasePrice(f)
	return puo
}

// SetRetailPrice sets the "retail_price" field.
func (puo *ProductUpdateOne) SetRetailPrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetRetailPrice()
	puo.mutation.SetRetailPrice(f)
	return puo
}

// SetNillableRetailPrice sets the "retail_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableRetailPrice(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetRetailPrice(*f)
	}
	return puo
}

// AddRetailPrice adds f to the "retail_price" field.
func (puo *ProductUpdateOne) AddRetailPrice(f float64) *ProductUpdateOne {
	puo.mutation.AddRetailPrice(f)
	return puo
}

// SetWholesalePrice sets the "wholesale_price" field.
func (puo *ProductUpdateOne) SetWholesalePrice(f float64) *ProductUpdateOne {
	puo.mutation.ResetWholesalePrice()
	puo.mutation.SetWholesalePrice(f)
	return puo
}

// SetNillableWholesalePrice sets the "wholesale_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableWholesalePrice(f *float64) *ProductUpdateOne {
	if f != nil {
		puo.SetWholesalePrice(*f)
	}
	return puo
}

// AddWholesalePrice adds f to the "wholesale_price" field.
func (puo *ProductUpdateOne) AddWholesalePrice(f float64) *ProductUpdateOne {
	puo.mutation.AddWholesalePrice(f)
	return puo
}

// ClearWholesalePrice clears the value of the "wholesale_price" field.
func (puo *ProductUpdateOne) ClearWholesalePrice() *ProductUpdateOne {
	puo.mutation.ClearWholesalePrice()
	return puo
}

// SetMinWholesaleQuantity sets the "min_wholesale_quantity" field.
func (puo *ProductUpdateOne) SetMinWholesaleQuantity(i int) *ProductUpdateOne {
	puo.mutation.ResetMinWholesaleQuantity()
	puo.mutation.SetMinWholesaleQuantity(i)
	return puo
}

// SetNillableMinWholesaleQuantity sets the "min_wholesale_quantity" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableMinWholesaleQuantity(i *int) *ProductUpdateOne {
	if i != nil {
		puo.SetMinWholesaleQuantity(*i)
	}
	return puo
}

// AddMinWholesaleQuantity adds i to the "min_wholesale_quantity" field.
func (puo *ProductUpdateOne) AddMinWholesaleQuantity(i int) *ProductUpdateOne {
	puo.mutation.AddMinWholesaleQuantity(i)
	return puo
}

// ClearMinWholesaleQuantity clears the value of the "min_wholesale_quantity" field.
func (puo *ProductUpdateOne) ClearMinWholesaleQuantity() *ProductUpdateOne {
	puo.mutation.ClearMinWholesaleQuantity()
	return puo
}

// SetStock sets the "stock" field.
func (puo *ProductUpdateOne) SetStock(i int) *ProductUpdateOne {
	puo.mutation.ResetStock()
	puo.mutation.SetStock(i)
	return puo
}

// SetNillableStock sets the "stock" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableStock(i *int) *ProductUpdateOne {
	if i != nil {
		puo.SetStock(*i)
	}
	return puo
}

// AddStock adds i to the "stock" field.
func (puo *ProductUpdateOne) AddStock(i int) *ProductUpdateOne {
	puo.mutation.AddStock(i)
	return puo
}

// SetSku sets the "sku" field.
func (puo *ProductUpdateOne) SetSku(s string) *ProductUpdateOne {
	puo.mutation.SetSku(s)
	return puo
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableSku(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetSku(*s)
	}
	return puo
}

// ClearSku clears the value of the "sku" field.
func (puo *ProductUpdateOne) ClearSku() *ProductUpdateOne {
	puo.mutation.ClearSku()
	return puo
}

// SetTenantID sets the "tenant_id" field.
func (puo *ProductUpdateOne) SetTenantID(i int) *ProductUpdateOne {
	puo.mutation.ResetTenantID()
	puo.mutation.SetTenantID(i)
	return puo
}

// AddTenantID adds i to the "tenant_id" field.
func (puo *ProductUpdateOne) AddTenantID(i int) *ProductUpdateOne {
	puo.mutation.AddTenantID(i)
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProductUpdateOne) SetUpdatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	var (
		err  error
		node *Product
	)
	puo.defaults()
	if len(puo.hooks) == 0 {
		if err = puo.check(); err != nil {
			return nil, err
		}
		node, err = puo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ProductMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = puo.check(); err != nil {
				return nil, err
			}
			puo.mutation = mutation
			node, err = puo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(puo.hooks) - 1; i >= 0; i-- {
			if puo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = puo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, puo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Product)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ProductMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProductUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := product.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProductUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Price(); ok {
		if err := product.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "Product.price": %w`, err)}
		}
	}
	if v, ok := puo.mutation.PurchasePrice(); ok {
		if err := product.PurchasePriceValidator(v); err != nil {
			return &ValidationError{Name: "purchase_price", err: fmt.Errorf(`ent: validator failed for field "Product.purchase_price": %w`, err)}
		}
	}
	if v, ok := puo.mutation.RetailPrice(); ok {
		if err := product.RetailPriceValidator(v); err != nil {
			return &ValidationError{Name: "retail_price", err: fmt.Errorf(`ent: validator failed for field "Product.retail_price": %w`, err)}
		}
	}
	if v, ok := puo.mutation.WholesalePrice(); ok {
		if err := product.WholesalePriceValidator(v); err != nil {
			return &ValidationError{Name: "wholesale_price", err: fmt.Errorf(`ent: validator failed for field "Product.wholesale_price": %w`, err)}
		}
	}
	if v, ok := puo.mutation.MinWholesaleQuantity(); ok {
		if err := product.MinWholesaleQuantityValidator(v); err != nil {
			return &ValidationError{Name: "min_wholesale_quantity", err: fmt.Errorf(`ent: validator failed for field "Product.min_wholesale_quantity": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Stock(); ok {
		if err := product.StockValidator(v); err != nil {
			return &ValidationError{Name: "stock", err: fmt.Errorf(`ent: validator failed for field "Product.stock": %w`, err)}
		}
	}
	return nil
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   product.Table,
			Columns: product.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: product.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldName,
		})
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldDescription,
		})
	}
	if puo.mutation.DescriptionCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: product.FieldDescription,
		})
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPrice,
		})
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPrice,
		})
	}
	if value, ok := puo.mutation.PurchasePrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPurchasePrice,
		})
	}
	if value, ok := puo.mutation.AddedPurchasePrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldPurchasePrice,
		})
	}
	if value, ok := puo.mutation.RetailPrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldRetailPrice,
		})
	}
	if value, ok := puo.mutation.AddedRetailPrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldRetailPrice,
		})
	}
	if value, ok := puo.mutation.WholesalePrice(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldWholesalePrice,
		})
	}
	if value, ok := puo.mutation.AddedWholesalePrice(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: product.FieldWholesalePrice,
		})
	}
	if puo.mutation.WholesalePriceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Column: product.FieldWholesalePrice,
		})
	}
	if value, ok := puo.mutation.MinWholesaleQuantity(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if value, ok := puo.mutation.AddedMinWholesaleQuantity(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if puo.mutation.MinWholesaleQuantityCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Column: product.FieldMinWholesaleQuantity,
		})
	}
	if value, ok := puo.mutation.Stock(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldStock,
		})
	}
	if value, ok := puo.mutation.AddedStock(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldStock,
		})
	}
	if value, ok := puo.mutation.Sku(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: product.FieldSku,
		})
	}
	if puo.mutation.SkuCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: product.FieldSku,
		})
	}
	if value, ok := puo.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldTenantID,
		})
	}
	if value, ok := puo.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: product.FieldTenantID,
		})
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: product.FieldUpdatedAt,
		})
	}
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
