// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/purchaseinvoice"
	"Veritasbackend/ent/supplier"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// PurchaseInvoice is the model entity for the PurchaseInvoice schema.
type PurchaseInvoice struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Número de factura del proveedor
	InvoiceNumber string `json:"invoice_number,omitempty"`
	// Total de la factura
	Total float64 `json:"total,omitempty"`
	// Estado de pago (pending, partial, paid, cancelled)
	Status string `json:"status,omitempty"`
	// Método de pago (cash, credit, partial)
	PaymentMethod string `json:"payment_method,omitempty"`
	// Fecha de vencimiento
	DueDate time.Time `json:"due_date,omitempty"`
	// Monto pagado hasta el momento
	PaidAmount float64 `json:"paid_amount,omitempty"`
	// ID del proveedor
	SupplierID int `json:"supplier_id,omitempty"`
	// ID del tenant
	TenantID int `json:"tenant_id,omitempty"`
	// ID del usuario que creó la factura
	UserID int `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PurchaseInvoiceQuery when eager-loading is set.
	Edges PurchaseInvoiceEdges `json:"edges"`
}

// PurchaseInvoiceEdges holds the relations/edges for other nodes in the graph.
type PurchaseInvoiceEdges struct {
	// Supplier holds the value of the supplier edge.
	Supplier *Supplier `json:"supplier,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SupplierOrErr returns the Supplier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PurchaseInvoiceEdges) SupplierOrErr() (*Supplier, error) {
	if e.loadedTypes[0] {
		if e.Supplier == nil {
			// The edge supplier was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: supplier.Label}
		}
		return e.Supplier, nil
	}
	return nil, &NotLoadedError{edge: "supplier"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PurchaseInvoice) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case purchaseinvoice.FieldTotal, purchaseinvoice.FieldPaidAmount:
			values[i] = new(sql.NullFloat64)
		case purchaseinvoice.FieldID, purchaseinvoice.FieldSupplierID, purchaseinvoice.FieldTenantID, purchaseinvoice.FieldUserID:
			values[i] = new(sql.NullInt64)
		case purchaseinvoice.FieldInvoiceNumber, purchaseinvoice.FieldStatus, purchaseinvoice.FieldPaymentMethod:
			values[i] = new(sql.NullString)
		case purchaseinvoice.FieldDueDate, purchaseinvoice.FieldCreatedAt, purchaseinvoice.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PurchaseInvoice", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PurchaseInvoice fields.
func (pi *PurchaseInvoice) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case purchaseinvoice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pi.ID = int(value.Int64)
		case purchaseinvoice.FieldInvoiceNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invoice_number", values[i])
			} else if value.Valid {
				pi.InvoiceNumber = value.String
			}
		case purchaseinvoice.FieldTotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value.Valid {
				pi.Total = value.Float64
			}
		case purchaseinvoice.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				pi.Status = value.String
			}
		case purchaseinvoice.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				pi.PaymentMethod = value.String
			}
		case purchaseinvoice.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				pi.DueDate = value.Time
			}
		case purchaseinvoice.FieldPaidAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_amount", values[i])
			} else if value.Valid {
				pi.PaidAmount = value.Float64
			}
		case purchaseinvoice.FieldSupplierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				pi.SupplierID = int(value.Int64)
			}
		case purchaseinvoice.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				pi.TenantID = int(value.Int64)
			}
		case purchaseinvoice.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				pi.UserID = int(value.Int64)
			}
		case purchaseinvoice.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pi.CreatedAt = value.Time
			}
		case purchaseinvoice.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pi.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QuerySupplier queries the "supplier" edge of the PurchaseInvoice entity.
func (pi *PurchaseInvoice) QuerySupplier() *SupplierQuery {
	return (&PurchaseInvoiceClient{config: pi.config}).QuerySupplier(pi)
}

// Update returns a builder for updating this PurchaseInvoice.
// Note that you need to call PurchaseInvoice.Unwrap() before calling this method if this PurchaseInvoice
// was returned from a transaction, and the transaction was committed or rolled back.
func (pi *PurchaseInvoice) Update() *PurchaseInvoiceUpdateOne {
	return (&PurchaseInvoiceClient{config: pi.config}).UpdateOne(pi)
}

// Unwrap unwraps the PurchaseInvoice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pi *PurchaseInvoice) Unwrap() *PurchaseInvoice {
	_tx, ok := pi.config.driver.(*txDriver)
	if !ok {
		panic("ent: PurchaseInvoice is not a transactional entity")
	}
	pi.config.driver = _tx.drv
	return pi
}

// String implements the fmt.Stringer.
func (pi *PurchaseInvoice) String() string {
	var builder strings.Builder
	builder.WriteString("PurchaseInvoice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pi.ID))
	builder.WriteString("invoice_number=")
	builder.WriteString(pi.InvoiceNumber)
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", pi.Total))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(pi.Status)
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(pi.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("due_date=")
	builder.WriteString(pi.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("paid_amount=")
	builder.WriteString(fmt.Sprintf("%v", pi.PaidAmount))
	builder.WriteString(", ")
	builder.WriteString("supplier_id=")
	builder.WriteString(fmt.Sprintf("%v", pi.SupplierID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", pi.TenantID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", pi.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pi.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pi.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PurchaseInvoices is a parsable slice of PurchaseInvoice.
type PurchaseInvoices []*PurchaseInvoice

func (pi PurchaseInvoices) config(cfg config) {
	for _i := range pi {
		pi[_i].config = cfg
	}
}
