// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/purchaseinvoiceitem"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// PurchaseInvoiceItem is the model entity for the PurchaseInvoiceItem schema.
type PurchaseInvoiceItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID de la factura de compra
	PurchaseInvoiceID int `json:"purchase_invoice_id,omitempty"`
	// ID del producto comprado
	ProductID int `json:"product_id,omitempty"`
	// Cantidad comprada
	Quantity int `json:"quantity,omitempty"`
	// Costo unitario al momento de la compra
	UnitCost float64 `json:"unit_cost,omitempty"`
	// Subtotal (quantity × unit_cost)
	Subtotal float64 `json:"subtotal,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PurchaseInvoiceItem) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case purchaseinvoiceitem.FieldUnitCost, purchaseinvoiceitem.FieldSubtotal:
			values[i] = new(sql.NullFloat64)
		case purchaseinvoiceitem.FieldID, purchaseinvoiceitem.FieldPurchaseInvoiceID, purchaseinvoiceitem.FieldProductID, purchaseinvoiceitem.FieldQuantity:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type PurchaseInvoiceItem", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PurchaseInvoiceItem fields.
func (pii *PurchaseInvoiceItem) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case purchaseinvoiceitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pii.ID = int(value.Int64)
		case purchaseinvoiceitem.FieldPurchaseInvoiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_invoice_id", values[i])
			} else if value.Valid {
				pii.PurchaseInvoiceID = int(value.Int64)
			}
		case purchaseinvoiceitem.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				pii.ProductID = int(value.Int64)
			}
		case purchaseinvoiceitem.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				pii.Quantity = int(value.Int64)
			}
		case purchaseinvoiceitem.FieldUnitCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field unit_cost", values[i])
			} else if value.Valid {
				pii.UnitCost = value.Float64
			}
		case purchaseinvoiceitem.FieldSubtotal:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field subtotal", values[i])
			} else if value.Valid {
				pii.Subtotal = value.Float64
			}
		}
	}
	return nil
}

// Update returns a builder for updating this PurchaseInvoiceItem.
// Note that you need to call PurchaseInvoiceItem.Unwrap() before calling this method if this PurchaseInvoiceItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (pii *PurchaseInvoiceItem) Update() *PurchaseInvoiceItemUpdateOne {
	return (&PurchaseInvoiceItemClient{config: pii.config}).UpdateOne(pii)
}

// Unwrap unwraps the PurchaseInvoiceItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pii *PurchaseInvoiceItem) Unwrap() *PurchaseInvoiceItem {
	_tx, ok := pii.config.driver.(*txDriver)
	if !ok {
		panic("ent: PurchaseInvoiceItem is not a transactional entity")
	}
	pii.config.driver = _tx.drv
	return pii
}

// String implements the fmt.Stringer.
func (pii *PurchaseInvoiceItem) String() string {
	var builder strings.Builder
	builder.WriteString("PurchaseInvoiceItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pii.ID))
	builder.WriteString("purchase_invoice_id=")
	builder.WriteString(fmt.Sprintf("%v", pii.PurchaseInvoiceID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", pii.ProductID))
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", pii.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit_cost=")
	builder.WriteString(fmt.Sprintf("%v", pii.UnitCost))
	builder.WriteString(", ")
	builder.WriteString("subtotal=")
	builder.WriteString(fmt.Sprintf("%v", pii.Subtotal))
	builder.WriteByte(')')
	return builder.String()
}

// PurchaseInvoiceItems is a parsable slice of PurchaseInvoiceItem.
type PurchaseInvoiceItems []*PurchaseInvoiceItem

func (pii PurchaseInvoiceItems) config(cfg config) {
	for _i := range pii {
		pii[_i].config = cfg
	}
}
