// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/predicate"
	"Veritasbackend/ent/purchaseinvoiceitem"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseInvoiceItemDelete is the builder for deleting a PurchaseInvoiceItem entity.
type PurchaseInvoiceItemDelete struct {
	config
	hooks    []Hook
	mutation *PurchaseInvoiceItemMutation
}

// Where appends a list predicates to the PurchaseInvoiceItemDelete builder.
func (piid *PurchaseInvoiceItemDelete) Where(ps ...predicate.PurchaseInvoiceItem) *PurchaseInvoiceItemDelete {
	piid.mutation.Where(ps...)
	return piid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (piid *PurchaseInvoiceItemDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(piid.hooks) == 0 {
		affected, err = piid.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PurchaseInvoiceItemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			piid.mutation = mutation
			affected, err = piid.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(piid.hooks) - 1; i >= 0; i-- {
			if piid.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = piid.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, piid.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (piid *PurchaseInvoiceItemDelete) ExecX(ctx context.Context) int {
	n, err := piid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (piid *PurchaseInvoiceItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: purchaseinvoiceitem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: purchaseinvoiceitem.FieldID,
			},
		},
	}
	if ps := piid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, piid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PurchaseInvoiceItemDeleteOne is the builder for deleting a single PurchaseInvoiceItem entity.
type PurchaseInvoiceItemDeleteOne struct {
	piid *PurchaseInvoiceItemDelete
}

// Exec executes the deletion query.
func (piido *PurchaseInvoiceItemDeleteOne) Exec(ctx context.Context) error {
	n, err := piido.piid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{purchaseinvoiceitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (piido *PurchaseInvoiceItemDeleteOne) ExecX(ctx context.Context) {
	piido.piid.ExecX(ctx)
}
