// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/predicate"
	"Veritasbackend/ent/purchaseinvoiceitem"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseInvoiceItemQuery is the builder for querying PurchaseInvoiceItem entities.
type PurchaseInvoiceItemQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PurchaseInvoiceItem
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PurchaseInvoiceItemQuery builder.
func (piiq *PurchaseInvoiceItemQuery) Where(ps ...predicate.PurchaseInvoiceItem) *PurchaseInvoiceItemQuery {
	piiq.predicates = append(piiq.predicates, ps...)
	return piiq
}

// Limit adds a limit step to the query.
func (piiq *PurchaseInvoiceItemQuery) Limit(limit int) *PurchaseInvoiceItemQuery {
	piiq.limit = &limit
	return piiq
}

// Offset adds an offset step to the query.
func (piiq *PurchaseInvoiceItemQuery) Offset(offset int) *PurchaseInvoiceItemQuery {
	piiq.offset = &offset
	return piiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piiq *PurchaseInvoiceItemQuery) Unique(unique bool) *PurchaseInvoiceItemQuery {
	piiq.unique = &unique
	return piiq
}

// Order adds an order step to the query.
func (piiq *PurchaseInvoiceItemQuery) Order(o ...OrderFunc) *PurchaseInvoiceItemQuery {
	piiq.order = append(piiq.order, o...)
	return piiq
}

// First returns the first PurchaseInvoiceItem entity from the query.
// Returns a *NotFoundError when no PurchaseInvoiceItem was found.
func (piiq *PurchaseInvoiceItemQuery) First(ctx context.Context) (*PurchaseInvoiceItem, error) {
	nodes, err := piiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{purchaseinvoiceitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) FirstX(ctx context.Context) *PurchaseInvoiceItem {
	node, err := piiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PurchaseInvoiceItem ID from the query.
// Returns a *NotFoundError when no PurchaseInvoiceItem ID was found.
func (piiq *PurchaseInvoiceItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{purchaseinvoiceitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) FirstIDX(ctx context.Context) int {
	id, err := piiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PurchaseInvoiceItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PurchaseInvoiceItem entity is found.
// Returns a *NotFoundError when no PurchaseInvoiceItem entities are found.
func (piiq *PurchaseInvoiceItemQuery) Only(ctx context.Context) (*PurchaseInvoiceItem, error) {
	nodes, err := piiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{purchaseinvoiceitem.Label}
	default:
		return nil, &NotSingularError{purchaseinvoiceitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) OnlyX(ctx context.Context) *PurchaseInvoiceItem {
	node, err := piiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PurchaseInvoiceItem ID in the query.
// Returns a *NotSingularError when more than one PurchaseInvoiceItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (piiq *PurchaseInvoiceItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = piiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{purchaseinvoiceitem.Label}
	default:
		err = &NotSingularError{purchaseinvoiceitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := piiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PurchaseInvoiceItems.
func (piiq *PurchaseInvoiceItemQuery) All(ctx context.Context) ([]*PurchaseInvoiceItem, error) {
	if err := piiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return piiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) AllX(ctx context.Context) []*PurchaseInvoiceItem {
	nodes, err := piiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PurchaseInvoiceItem IDs.
func (piiq *PurchaseInvoiceItemQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := piiq.Select(purchaseinvoiceitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) IDsX(ctx context.Context) []int {
	ids, err := piiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piiq *PurchaseInvoiceItemQuery) Count(ctx context.Context) (int, error) {
	if err := piiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return piiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) CountX(ctx context.Context) int {
	count, err := piiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piiq *PurchaseInvoiceItemQuery) Exist(ctx context.Context) (bool, error) {
	if err := piiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return piiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (piiq *PurchaseInvoiceItemQuery) ExistX(ctx context.Context) bool {
	exist, err := piiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PurchaseInvoiceItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piiq *PurchaseInvoiceItemQuery) Clone() *PurchaseInvoiceItemQuery {
	if piiq == nil {
		return nil
	}
	return &PurchaseInvoiceItemQuery{
		config:     piiq.config,
		limit:      piiq.limit,
		offset:     piiq.offset,
		order:      append([]OrderFunc{}, piiq.order...),
		predicates: append([]predicate.PurchaseInvoiceItem{}, piiq.predicates...),
		// clone intermediate query.
		sql:    piiq.sql.Clone(),
		path:   piiq.path,
		unique: piiq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PurchaseInvoiceID int `json:"purchase_invoice_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PurchaseInvoiceItem.Query().
//		GroupBy(purchaseinvoiceitem.FieldPurchaseInvoiceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (piiq *PurchaseInvoiceItemQuery) GroupBy(field string, fields ...string) *PurchaseInvoiceItemGroupBy {
	grbuild := &PurchaseInvoiceItemGroupBy{config: piiq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := piiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return piiq.sqlQuery(ctx), nil
	}
	grbuild.label = purchaseinvoiceitem.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PurchaseInvoiceID int `json:"purchase_invoice_id,omitempty"`
//	}
//
//	client.PurchaseInvoiceItem.Query().
//		Select(purchaseinvoiceitem.FieldPurchaseInvoiceID).
//		Scan(ctx, &v)
//
func (piiq *PurchaseInvoiceItemQuery) Select(fields ...string) *PurchaseInvoiceItemSelect {
	piiq.fields = append(piiq.fields, fields...)
	selbuild := &PurchaseInvoiceItemSelect{PurchaseInvoiceItemQuery: piiq}
	selbuild.label = purchaseinvoiceitem.Label
	selbuild.flds, selbuild.scan = &piiq.fields, selbuild.Scan
	return selbuild
}

func (piiq *PurchaseInvoiceItemQuery) prepareQuery(ctx context.Context) error {
	for _, f := range piiq.fields {
		if !purchaseinvoiceitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piiq.path != nil {
		prev, err := piiq.path(ctx)
		if err != nil {
			return err
		}
		piiq.sql = prev
	}
	return nil
}

func (piiq *PurchaseInvoiceItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PurchaseInvoiceItem, error) {
	var (
		nodes = []*PurchaseInvoiceItem{}
		_spec = piiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*PurchaseInvoiceItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &PurchaseInvoiceItem{config: piiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (piiq *PurchaseInvoiceItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piiq.querySpec()
	_spec.Node.Columns = piiq.fields
	if len(piiq.fields) > 0 {
		_spec.Unique = piiq.unique != nil && *piiq.unique
	}
	return sqlgraph.CountNodes(ctx, piiq.driver, _spec)
}

func (piiq *PurchaseInvoiceItemQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := piiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (piiq *PurchaseInvoiceItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   purchaseinvoiceitem.Table,
			Columns: purchaseinvoiceitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: purchaseinvoiceitem.FieldID,
			},
		},
		From:   piiq.sql,
		Unique: true,
	}
	if unique := piiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := piiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, purchaseinvoiceitem.FieldID)
		for i := range fields {
			if fields[i] != purchaseinvoiceitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piiq *PurchaseInvoiceItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piiq.driver.Dialect())
	t1 := builder.Table(purchaseinvoiceitem.Table)
	columns := piiq.fields
	if len(columns) == 0 {
		columns = purchaseinvoiceitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piiq.sql != nil {
		selector = piiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piiq.unique != nil && *piiq.unique {
		selector.Distinct()
	}
	for _, p := range piiq.predicates {
		p(selector)
	}
	for _, p := range piiq.order {
		p(selector)
	}
	if offset := piiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PurchaseInvoiceItemGroupBy is the group-by builder for PurchaseInvoiceItem entities.
type PurchaseInvoiceItemGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (piigb *PurchaseInvoiceItemGroupBy) Aggregate(fns ...AggregateFunc) *PurchaseInvoiceItemGroupBy {
	piigb.fns = append(piigb.fns, fns...)
	return piigb
}

// Scan applies the group-by query and scans the result into the given value.
func (piigb *PurchaseInvoiceItemGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := piigb.path(ctx)
	if err != nil {
		return err
	}
	piigb.sql = query
	return piigb.sqlScan(ctx, v)
}

func (piigb *PurchaseInvoiceItemGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range piigb.fields {
		if !purchaseinvoiceitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := piigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := piigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (piigb *PurchaseInvoiceItemGroupBy) sqlQuery() *sql.Selector {
	selector := piigb.sql.Select()
	aggregation := make([]string, 0, len(piigb.fns))
	for _, fn := range piigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(piigb.fields)+len(piigb.fns))
		for _, f := range piigb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(piigb.fields...)...)
}

// PurchaseInvoiceItemSelect is the builder for selecting fields of PurchaseInvoiceItem entities.
type PurchaseInvoiceItemSelect struct {
	*PurchaseInvoiceItemQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (piis *PurchaseInvoiceItemSelect) Scan(ctx context.Context, v interface{}) error {
	if err := piis.prepareQuery(ctx); err != nil {
		return err
	}
	piis.sql = piis.PurchaseInvoiceItemQuery.sqlQuery(ctx)
	return piis.sqlScan(ctx, v)
}

func (piis *PurchaseInvoiceItemSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := piis.sql.Query()
	if err := piis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
