// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/purchaseinvoice"
	"Veritasbackend/ent/supplier"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PurchaseInvoiceCreate is the builder for creating a PurchaseInvoice entity.
type PurchaseInvoiceCreate struct {
	config
	mutation *PurchaseInvoiceMutation
	hooks    []Hook
}

// SetInvoiceNumber sets the "invoice_number" field.
func (pic *PurchaseInvoiceCreate) SetInvoiceNumber(s string) *PurchaseInvoiceCreate {
	pic.mutation.SetInvoiceNumber(s)
	return pic
}

// SetTotal sets the "total" field.
func (pic *PurchaseInvoiceCreate) SetTotal(f float64) *PurchaseInvoiceCreate {
	pic.mutation.SetTotal(f)
	return pic
}

// SetStatus sets the "status" field.
func (pic *PurchaseInvoiceCreate) SetStatus(s string) *PurchaseInvoiceCreate {
	pic.mutation.SetStatus(s)
	return pic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillableStatus(s *string) *PurchaseInvoiceCreate {
	if s != nil {
		pic.SetStatus(*s)
	}
	return pic
}

// SetPaymentMethod sets the "payment_method" field.
func (pic *PurchaseInvoiceCreate) SetPaymentMethod(s string) *PurchaseInvoiceCreate {
	pic.mutation.SetPaymentMethod(s)
	return pic
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillablePaymentMethod(s *string) *PurchaseInvoiceCreate {
	if s != nil {
		pic.SetPaymentMethod(*s)
	}
	return pic
}

// SetDueDate sets the "due_date" field.
func (pic *PurchaseInvoiceCreate) SetDueDate(t time.Time) *PurchaseInvoiceCreate {
	pic.mutation.SetDueDate(t)
	return pic
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillableDueDate(t *time.Time) *PurchaseInvoiceCreate {
	if t != nil {
		pic.SetDueDate(*t)
	}
	return pic
}

// SetPaidAmount sets the "paid_amount" field.
func (pic *PurchaseInvoiceCreate) SetPaidAmount(f float64) *PurchaseInvoiceCreate {
	pic.mutation.SetPaidAmount(f)
	return pic
}

// SetNillablePaidAmount sets the "paid_amount" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillablePaidAmount(f *float64) *PurchaseInvoiceCreate {
	if f != nil {
		pic.SetPaidAmount(*f)
	}
	return pic
}

// SetSupplierID sets the "supplier_id" field.
func (pic *PurchaseInvoiceCreate) SetSupplierID(i int) *PurchaseInvoiceCreate {
	pic.mutation.SetSupplierID(i)
	return pic
}

// SetTenantID sets the "tenant_id" field.
func (pic *PurchaseInvoiceCreate) SetTenantID(i int) *PurchaseInvoiceCreate {
	pic.mutation.SetTenantID(i)
	return pic
}

// SetUserID sets the "user_id" field.
func (pic *PurchaseInvoiceCreate) SetUserID(i int) *PurchaseInvoiceCreate {
	pic.mutation.SetUserID(i)
	return pic
}

// SetCreatedAt sets the "created_at" field.
func (pic *PurchaseInvoiceCreate) SetCreatedAt(t time.Time) *PurchaseInvoiceCreate {
	pic.mutation.SetCreatedAt(t)
	return pic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillableCreatedAt(t *time.Time) *PurchaseInvoiceCreate {
	if t != nil {
		pic.SetCreatedAt(*t)
	}
	return pic
}

// SetUpdatedAt sets the "updated_at" field.
func (pic *PurchaseInvoiceCreate) SetUpdatedAt(t time.Time) *PurchaseInvoiceCreate {
	pic.mutation.SetUpdatedAt(t)
	return pic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pic *PurchaseInvoiceCreate) SetNillableUpdatedAt(t *time.Time) *PurchaseInvoiceCreate {
	if t != nil {
		pic.SetUpdatedAt(*t)
	}
	return pic
}

// SetSupplier sets the "supplier" edge to the Supplier entity.
func (pic *PurchaseInvoiceCreate) SetSupplier(s *Supplier) *PurchaseInvoiceCreate {
	return pic.SetSupplierID(s.ID)
}

// Mutation returns the PurchaseInvoiceMutation object of the builder.
func (pic *PurchaseInvoiceCreate) Mutation() *PurchaseInvoiceMutation {
	return pic.mutation
}

// Save creates the PurchaseInvoice in the database.
func (pic *PurchaseInvoiceCreate) Save(ctx context.Context) (*PurchaseInvoice, error) {
	var (
		err  error
		node *PurchaseInvoice
	)
	pic.defaults()
	if len(pic.hooks) == 0 {
		if err = pic.check(); err != nil {
			return nil, err
		}
		node, err = pic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PurchaseInvoiceMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pic.check(); err != nil {
				return nil, err
			}
			pic.mutation = mutation
			if node, err = pic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pic.hooks) - 1; i >= 0; i-- {
			if pic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, pic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*PurchaseInvoice)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from PurchaseInvoiceMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pic *PurchaseInvoiceCreate) SaveX(ctx context.Context) *PurchaseInvoice {
	v, err := pic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pic *PurchaseInvoiceCreate) Exec(ctx context.Context) error {
	_, err := pic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pic *PurchaseInvoiceCreate) ExecX(ctx context.Context) {
	if err := pic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pic *PurchaseInvoiceCreate) defaults() {
	if _, ok := pic.mutation.Status(); !ok {
		v := purchaseinvoice.DefaultStatus
		pic.mutation.SetStatus(v)
	}
	if _, ok := pic.mutation.PaidAmount(); !ok {
		v := purchaseinvoice.DefaultPaidAmount
		pic.mutation.SetPaidAmount(v)
	}
	if _, ok := pic.mutation.CreatedAt(); !ok {
		v := purchaseinvoice.DefaultCreatedAt()
		pic.mutation.SetCreatedAt(v)
	}
	if _, ok := pic.mutation.UpdatedAt(); !ok {
		v := purchaseinvoice.DefaultUpdatedAt()
		pic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pic *PurchaseInvoiceCreate) check() error {
	if _, ok := pic.mutation.InvoiceNumber(); !ok {
		return &ValidationError{Name: "invoice_number", err: errors.New(`ent: missing required field "PurchaseInvoice.invoice_number"`)}
	}
	if v, ok := pic.mutation.InvoiceNumber(); ok {
		if err := purchaseinvoice.InvoiceNumberValidator(v); err != nil {
			return &ValidationError{Name: "invoice_number", err: fmt.Errorf(`ent: validator failed for field "PurchaseInvoice.invoice_number": %w`, err)}
		}
	}
	if _, ok := pic.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "PurchaseInvoice.total"`)}
	}
	if v, ok := pic.mutation.Total(); ok {
		if err := purchaseinvoice.TotalValidator(v); err != nil {
			return &ValidationError{Name: "total", err: fmt.Errorf(`ent: validator failed for field "PurchaseInvoice.total": %w`, err)}
		}
	}
	if _, ok := pic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PurchaseInvoice.status"`)}
	}
	if _, ok := pic.mutation.PaidAmount(); !ok {
		return &ValidationError{Name: "paid_amount", err: errors.New(`ent: missing required field "PurchaseInvoice.paid_amount"`)}
	}
	if v, ok := pic.mutation.PaidAmount(); ok {
		if err := purchaseinvoice.PaidAmountValidator(v); err != nil {
			return &ValidationError{Name: "paid_amount", err: fmt.Errorf(`ent: validator failed for field "PurchaseInvoice.paid_amount": %w`, err)}
		}
	}
	if _, ok := pic.mutation.SupplierID(); !ok {
		return &ValidationError{Name: "supplier_id", err: errors.New(`ent: missing required field "PurchaseInvoice.supplier_id"`)}
	}
	if _, ok := pic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PurchaseInvoice.tenant_id"`)}
	}
	if _, ok := pic.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PurchaseInvoice.user_id"`)}
	}
	if _, ok := pic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PurchaseInvoice.created_at"`)}
	}
	if _, ok := pic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PurchaseInvoice.updated_at"`)}
	}
	if _, ok := pic.mutation.SupplierID(); !ok {
		return &ValidationError{Name: "supplier", err: errors.New(`ent: missing required edge "PurchaseInvoice.supplier"`)}
	}
	return nil
}

func (pic *PurchaseInvoiceCreate) sqlSave(ctx context.Context) (*PurchaseInvoice, error) {
	_node, _spec := pic.createSpec()
	if err := sqlgraph.CreateNode(ctx, pic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (pic *PurchaseInvoiceCreate) createSpec() (*PurchaseInvoice, *sqlgraph.CreateSpec) {
	var (
		_node = &PurchaseInvoice{config: pic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: purchaseinvoice.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: purchaseinvoice.FieldID,
			},
		}
	)
	if value, ok := pic.mutation.InvoiceNumber(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: purchaseinvoice.FieldInvoiceNumber,
		})
		_node.InvoiceNumber = value
	}
	if value, ok := pic.mutation.Total(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: purchaseinvoice.FieldTotal,
		})
		_node.Total = value
	}
	if value, ok := pic.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: purchaseinvoice.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := pic.mutation.PaymentMethod(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: purchaseinvoice.FieldPaymentMethod,
		})
		_node.PaymentMethod = value
	}
	if value, ok := pic.mutation.DueDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: purchaseinvoice.FieldDueDate,
		})
		_node.DueDate = value
	}
	if value, ok := pic.mutation.PaidAmount(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: purchaseinvoice.FieldPaidAmount,
		})
		_node.PaidAmount = value
	}
	if value, ok := pic.mutation.TenantID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: purchaseinvoice.FieldTenantID,
		})
		_node.TenantID = value
	}
	if value, ok := pic.mutation.UserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: purchaseinvoice.FieldUserID,
		})
		_node.UserID = value
	}
	if value, ok := pic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: purchaseinvoice.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pic.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: purchaseinvoice.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := pic.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   purchaseinvoice.SupplierTable,
			Columns: []string{purchaseinvoice.SupplierColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: supplier.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SupplierID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PurchaseInvoiceCreateBulk is the builder for creating many PurchaseInvoice entities in bulk.
type PurchaseInvoiceCreateBulk struct {
	config
	builders []*PurchaseInvoiceCreate
}

// Save creates the PurchaseInvoice entities in the database.
func (picb *PurchaseInvoiceCreateBulk) Save(ctx context.Context) ([]*PurchaseInvoice, error) {
	specs := make([]*sqlgraph.CreateSpec, len(picb.builders))
	nodes := make([]*PurchaseInvoice, len(picb.builders))
	mutators := make([]Mutator, len(picb.builders))
	for i := range picb.builders {
		func(i int, root context.Context) {
			builder := picb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseInvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, picb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, picb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, picb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (picb *PurchaseInvoiceCreateBulk) SaveX(ctx context.Context) []*PurchaseInvoice {
	v, err := picb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (picb *PurchaseInvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := picb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (picb *PurchaseInvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := picb.Exec(ctx); err != nil {
		panic(err)
	}
}
