// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/predicate"
	"Veritasbackend/ent/supplierpayment"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupplierPaymentUpdate is the builder for updating SupplierPayment entities.
type SupplierPaymentUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierPaymentMutation
}

// Where appends a list predicates to the SupplierPaymentUpdate builder.
func (spu *SupplierPaymentUpdate) Where(ps ...predicate.SupplierPayment) *SupplierPaymentUpdate {
	spu.mutation.Where(ps...)
	return spu
}

// SetPurchaseInvoiceID sets the "purchase_invoice_id" field.
func (spu *SupplierPaymentUpdate) SetPurchaseInvoiceID(i int) *SupplierPaymentUpdate {
	spu.mutation.ResetPurchaseInvoiceID()
	spu.mutation.SetPurchaseInvoiceID(i)
	return spu
}

// AddPurchaseInvoiceID adds i to the "purchase_invoice_id" field.
func (spu *SupplierPaymentUpdate) AddPurchaseInvoiceID(i int) *SupplierPaymentUpdate {
	spu.mutation.AddPurchaseInvoiceID(i)
	return spu
}

// SetSupplierID sets the "supplier_id" field.
func (spu *SupplierPaymentUpdate) SetSupplierID(i int) *SupplierPaymentUpdate {
	spu.mutation.ResetSupplierID()
	spu.mutation.SetSupplierID(i)
	return spu
}

// AddSupplierID adds i to the "supplier_id" field.
func (spu *SupplierPaymentUpdate) AddSupplierID(i int) *SupplierPaymentUpdate {
	spu.mutation.AddSupplierID(i)
	return spu
}

// SetAmount sets the "amount" field.
func (spu *SupplierPaymentUpdate) SetAmount(f float64) *SupplierPaymentUpdate {
	spu.mutation.ResetAmount()
	spu.mutation.SetAmount(f)
	return spu
}

// AddAmount adds f to the "amount" field.
func (spu *SupplierPaymentUpdate) AddAmount(f float64) *SupplierPaymentUpdate {
	spu.mutation.AddAmount(f)
	return spu
}

// SetPaymentDate sets the "payment_date" field.
func (spu *SupplierPaymentUpdate) SetPaymentDate(t time.Time) *SupplierPaymentUpdate {
	spu.mutation.SetPaymentDate(t)
	return spu
}

// SetNillablePaymentDate sets the "payment_date" field if the given value is not nil.
func (spu *SupplierPaymentUpdate) SetNillablePaymentDate(t *time.Time) *SupplierPaymentUpdate {
	if t != nil {
		spu.SetPaymentDate(*t)
	}
	return spu
}

// SetPaymentMethod sets the "payment_method" field.
func (spu *SupplierPaymentUpdate) SetPaymentMethod(s string) *SupplierPaymentUpdate {
	spu.mutation.SetPaymentMethod(s)
	return spu
}

// SetReference sets the "reference" field.
func (spu *SupplierPaymentUpdate) SetReference(s string) *SupplierPaymentUpdate {
	spu.mutation.SetReference(s)
	return spu
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (spu *SupplierPaymentUpdate) SetNillableReference(s *string) *SupplierPaymentUpdate {
	if s != nil {
		spu.SetReference(*s)
	}
	return spu
}

// ClearReference clears the value of the "reference" field.
func (spu *SupplierPaymentUpdate) ClearReference() *SupplierPaymentUpdate {
	spu.mutation.ClearReference()
	return spu
}

// SetNotes sets the "notes" field.
func (spu *SupplierPaymentUpdate) SetNotes(s string) *SupplierPaymentUpdate {
	spu.mutation.SetNotes(s)
	return spu
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (spu *SupplierPaymentUpdate) SetNillableNotes(s *string) *SupplierPaymentUpdate {
	if s != nil {
		spu.SetNotes(*s)
	}
	return spu
}

// ClearNotes clears the value of the "notes" field.
func (spu *SupplierPaymentUpdate) ClearNotes() *SupplierPaymentUpdate {
	spu.mutation.ClearNotes()
	return spu
}

// SetTenantID sets the "tenant_id" field.
func (spu *SupplierPaymentUpdate) SetTenantID(i int) *SupplierPaymentUpdate {
	spu.mutation.ResetTenantID()
	spu.mutation.SetTenantID(i)
	return spu
}

// AddTenantID adds i to the "tenant_id" field.
func (spu *SupplierPaymentUpdate) AddTenantID(i int) *SupplierPaymentUpdate {
	spu.mutation.AddTenantID(i)
	return spu
}

// SetUserID sets the "user_id" field.
func (spu *SupplierPaymentUpdate) SetUserID(i int) *SupplierPaymentUpdate {
	spu.mutation.ResetUserID()
	spu.mutation.SetUserID(i)
	return spu
}

// AddUserID adds i to the "user_id" field.
func (spu *SupplierPaymentUpdate) AddUserID(i int) *SupplierPaymentUpdate {
	spu.mutation.AddUserID(i)
	return spu
}

// SetUpdatedAt sets the "updated_at" field.
func (spu *SupplierPaymentUpdate) SetUpdatedAt(t time.Time) *SupplierPaymentUpdate {
	spu.mutation.SetUpdatedAt(t)
	return spu
}

// Mutation returns the SupplierPaymentMutation object of the builder.
func (spu *SupplierPaymentUpdate) Mutation() *SupplierPaymentMutation {
	return spu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (spu *SupplierPaymentUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	spu.defaults()
	if len(spu.hooks) == 0 {
		if err = spu.check(); err != nil {
			return 0, err
		}
		affected, err = spu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SupplierPaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = spu.check(); err != nil {
				return 0, err
			}
			spu.mutation = mutation
			affected, err = spu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(spu.hooks) - 1; i >= 0; i-- {
			if spu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, spu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (spu *SupplierPaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := spu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (spu *SupplierPaymentUpdate) Exec(ctx context.Context) error {
	_, err := spu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spu *SupplierPaymentUpdate) ExecX(ctx context.Context) {
	if err := spu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (spu *SupplierPaymentUpdate) defaults() {
	if _, ok := spu.mutation.UpdatedAt(); !ok {
		v := supplierpayment.UpdateDefaultUpdatedAt()
		spu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (spu *SupplierPaymentUpdate) check() error {
	if v, ok := spu.mutation.Amount(); ok {
		if err := supplierpayment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "SupplierPayment.amount": %w`, err)}
		}
	}
	if v, ok := spu.mutation.PaymentMethod(); ok {
		if err := supplierpayment.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "SupplierPayment.payment_method": %w`, err)}
		}
	}
	return nil
}

func (spu *SupplierPaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   supplierpayment.Table,
			Columns: supplierpayment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplierpayment.FieldID,
			},
		},
	}
	if ps := spu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spu.mutation.PurchaseInvoiceID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldPurchaseInvoiceID,
		})
	}
	if value, ok := spu.mutation.AddedPurchaseInvoiceID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldPurchaseInvoiceID,
		})
	}
	if value, ok := spu.mutation.SupplierID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldSupplierID,
		})
	}
	if value, ok := spu.mutation.AddedSupplierID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldSupplierID,
		})
	}
	if value, ok := spu.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: supplierpayment.FieldAmount,
		})
	}
	if value, ok := spu.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: supplierpayment.FieldAmount,
		})
	}
	if value, ok := spu.mutation.PaymentDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplierpayment.FieldPaymentDate,
		})
	}
	if value, ok := spu.mutation.PaymentMethod(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldPaymentMethod,
		})
	}
	if value, ok := spu.mutation.Reference(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldReference,
		})
	}
	if spu.mutation.ReferenceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplierpayment.FieldReference,
		})
	}
	if value, ok := spu.mutation.Notes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldNotes,
		})
	}
	if spu.mutation.NotesCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplierpayment.FieldNotes,
		})
	}
	if value, ok := spu.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldTenantID,
		})
	}
	if value, ok := spu.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldTenantID,
		})
	}
	if value, ok := spu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldUserID,
		})
	}
	if value, ok := spu.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldUserID,
		})
	}
	if value, ok := spu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplierpayment.FieldUpdatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, spu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SupplierPaymentUpdateOne is the builder for updating a single SupplierPayment entity.
type SupplierPaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierPaymentMutation
}

// SetPurchaseInvoiceID sets the "purchase_invoice_id" field.
func (spuo *SupplierPaymentUpdateOne) SetPurchaseInvoiceID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.ResetPurchaseInvoiceID()
	spuo.mutation.SetPurchaseInvoiceID(i)
	return spuo
}

// AddPurchaseInvoiceID adds i to the "purchase_invoice_id" field.
func (spuo *SupplierPaymentUpdateOne) AddPurchaseInvoiceID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.AddPurchaseInvoiceID(i)
	return spuo
}

// SetSupplierID sets the "supplier_id" field.
func (spuo *SupplierPaymentUpdateOne) SetSupplierID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.ResetSupplierID()
	spuo.mutation.SetSupplierID(i)
	return spuo
}

// AddSupplierID adds i to the "supplier_id" field.
func (spuo *SupplierPaymentUpdateOne) AddSupplierID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.AddSupplierID(i)
	return spuo
}

// SetAmount sets the "amount" field.
func (spuo *SupplierPaymentUpdateOne) SetAmount(f float64) *SupplierPaymentUpdateOne {
	spuo.mutation.ResetAmount()
	spuo.mutation.SetAmount(f)
	return spuo
}

// AddAmount adds f to the "amount" field.
func (spuo *SupplierPaymentUpdateOne) AddAmount(f float64) *SupplierPaymentUpdateOne {
	spuo.mutation.AddAmount(f)
	return spuo
}

// SetPaymentDate sets the "payment_date" field.
func (spuo *SupplierPaymentUpdateOne) SetPaymentDate(t time.Time) *SupplierPaymentUpdateOne {
	spuo.mutation.SetPaymentDate(t)
	return spuo
}

// SetNillablePaymentDate sets the "payment_date" field if the given value is not nil.
func (spuo *SupplierPaymentUpdateOne) SetNillablePaymentDate(t *time.Time) *SupplierPaymentUpdateOne {
	if t != nil {
		spuo.SetPaymentDate(*t)
	}
	return spuo
}

// SetPaymentMethod sets the "payment_method" field.
func (spuo *SupplierPaymentUpdateOne) SetPaymentMethod(s string) *SupplierPaymentUpdateOne {
	spuo.mutation.SetPaymentMethod(s)
	return spuo
}

// SetReference sets the "reference" field.
func (spuo *SupplierPaymentUpdateOne) SetReference(s string) *SupplierPaymentUpdateOne {
	spuo.mutation.SetReference(s)
	return spuo
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (spuo *SupplierPaymentUpdateOne) SetNillableReference(s *string) *SupplierPaymentUpdateOne {
	if s != nil {
		spuo.SetReference(*s)
	}
	return spuo
}

// ClearReference clears the value of the "reference" field.
func (spuo *SupplierPaymentUpdateOne) ClearReference() *SupplierPaymentUpdateOne {
	spuo.mutation.ClearReference()
	return spuo
}

// SetNotes sets the "notes" field.
func (spuo *SupplierPaymentUpdateOne) SetNotes(s string) *SupplierPaymentUpdateOne {
	spuo.mutation.SetNotes(s)
	return spuo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (spuo *SupplierPaymentUpdateOne) SetNillableNotes(s *string) *SupplierPaymentUpdateOne {
	if s != nil {
		spuo.SetNotes(*s)
	}
	return spuo
}

// ClearNotes clears the value of the "notes" field.
func (spuo *SupplierPaymentUpdateOne) ClearNotes() *SupplierPaymentUpdateOne {
	spuo.mutation.ClearNotes()
	return spuo
}

// SetTenantID sets the "tenant_id" field.
func (spuo *SupplierPaymentUpdateOne) SetTenantID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.ResetTenantID()
	spuo.mutation.SetTenantID(i)
	return spuo
}

// AddTenantID adds i to the "tenant_id" field.
func (spuo *SupplierPaymentUpdateOne) AddTenantID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.AddTenantID(i)
	return spuo
}

// SetUserID sets the "user_id" field.
func (spuo *SupplierPaymentUpdateOne) SetUserID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.ResetUserID()
	spuo.mutation.SetUserID(i)
	return spuo
}

// AddUserID adds i to the "user_id" field.
func (spuo *SupplierPaymentUpdateOne) AddUserID(i int) *SupplierPaymentUpdateOne {
	spuo.mutation.AddUserID(i)
	return spuo
}

// SetUpdatedAt sets the "updated_at" field.
func (spuo *SupplierPaymentUpdateOne) SetUpdatedAt(t time.Time) *SupplierPaymentUpdateOne {
	spuo.mutation.SetUpdatedAt(t)
	return spuo
}

// Mutation returns the SupplierPaymentMutation object of the builder.
func (spuo *SupplierPaymentUpdateOne) Mutation() *SupplierPaymentMutation {
	return spuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (spuo *SupplierPaymentUpdateOne) Select(field string, fields ...string) *SupplierPaymentUpdateOne {
	spuo.fields = append([]string{field}, fields...)
	return spuo
}

// Save executes the query and returns the updated SupplierPayment entity.
func (spuo *SupplierPaymentUpdateOne) Save(ctx context.Context) (*SupplierPayment, error) {
	var (
		err  error
		node *SupplierPayment
	)
	spuo.defaults()
	if len(spuo.hooks) == 0 {
		if err = spuo.check(); err != nil {
			return nil, err
		}
		node, err = spuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SupplierPaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = spuo.check(); err != nil {
				return nil, err
			}
			spuo.mutation = mutation
			node, err = spuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(spuo.hooks) - 1; i >= 0; i-- {
			if spuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = spuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, spuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*SupplierPayment)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SupplierPaymentMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (spuo *SupplierPaymentUpdateOne) SaveX(ctx context.Context) *SupplierPayment {
	node, err := spuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (spuo *SupplierPaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := spuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (spuo *SupplierPaymentUpdateOne) ExecX(ctx context.Context) {
	if err := spuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (spuo *SupplierPaymentUpdateOne) defaults() {
	if _, ok := spuo.mutation.UpdatedAt(); !ok {
		v := supplierpayment.UpdateDefaultUpdatedAt()
		spuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (spuo *SupplierPaymentUpdateOne) check() error {
	if v, ok := spuo.mutation.Amount(); ok {
		if err := supplierpayment.AmountValidator(v); err != nil {
			return &ValidationError{Name: "amount", err: fmt.Errorf(`ent: validator failed for field "SupplierPayment.amount": %w`, err)}
		}
	}
	if v, ok := spuo.mutation.PaymentMethod(); ok {
		if err := supplierpayment.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "SupplierPayment.payment_method": %w`, err)}
		}
	}
	return nil
}

func (spuo *SupplierPaymentUpdateOne) sqlSave(ctx context.Context) (_node *SupplierPayment, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   supplierpayment.Table,
			Columns: supplierpayment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplierpayment.FieldID,
			},
		},
	}
	id, ok := spuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupplierPayment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := spuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplierpayment.FieldID)
		for _, f := range fields {
			if !supplierpayment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplierpayment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := spuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := spuo.mutation.PurchaseInvoiceID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldPurchaseInvoiceID,
		})
	}
	if value, ok := spuo.mutation.AddedPurchaseInvoiceID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldPurchaseInvoiceID,
		})
	}
	if value, ok := spuo.mutation.SupplierID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldSupplierID,
		})
	}
	if value, ok := spuo.mutation.AddedSupplierID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldSupplierID,
		})
	}
	if value, ok := spuo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: supplierpayment.FieldAmount,
		})
	}
	if value, ok := spuo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: supplierpayment.FieldAmount,
		})
	}
	if value, ok := spuo.mutation.PaymentDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplierpayment.FieldPaymentDate,
		})
	}
	if value, ok := spuo.mutation.PaymentMethod(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldPaymentMethod,
		})
	}
	if value, ok := spuo.mutation.Reference(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldReference,
		})
	}
	if spuo.mutation.ReferenceCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplierpayment.FieldReference,
		})
	}
	if value, ok := spuo.mutation.Notes(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplierpayment.FieldNotes,
		})
	}
	if spuo.mutation.NotesCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplierpayment.FieldNotes,
		})
	}
	if value, ok := spuo.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldTenantID,
		})
	}
	if value, ok := spuo.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldTenantID,
		})
	}
	if value, ok := spuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldUserID,
		})
	}
	if value, ok := spuo.mutation.AddedUserID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplierpayment.FieldUserID,
		})
	}
	if value, ok := spuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplierpayment.FieldUpdatedAt,
		})
	}
	_node = &SupplierPayment{config: spuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, spuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
