// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/supplier"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// Supplier is the model entity for the Supplier schema.
type Supplier struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nombre del proveedor
	Name string `json:"name,omitempty"`
	// Email de contacto
	Email string `json:"email,omitempty"`
	// Teléfono de contacto
	Phone string `json:"phone,omitempty"`
	// Dirección del proveedor
	Address string `json:"address,omitempty"`
	// Número de identificación fiscal (RUC/NIT)
	RucNit string `json:"ruc_nit,omitempty"`
	// ID del tenant al que pertenece
	TenantID int `json:"tenant_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupplierQuery when eager-loading is set.
	Edges SupplierEdges `json:"edges"`
}

// SupplierEdges holds the relations/edges for other nodes in the graph.
type SupplierEdges struct {
	// PurchaseInvoices holds the value of the purchase_invoices edge.
	PurchaseInvoices []*PurchaseInvoice `json:"purchase_invoices,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PurchaseInvoicesOrErr returns the PurchaseInvoices value or an error if the edge
// was not loaded in eager-loading.
func (e SupplierEdges) PurchaseInvoicesOrErr() ([]*PurchaseInvoice, error) {
	if e.loadedTypes[0] {
		return e.PurchaseInvoices, nil
	}
	return nil, &NotLoadedError{edge: "purchase_invoices"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Supplier) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplier.FieldID, supplier.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case supplier.FieldName, supplier.FieldEmail, supplier.FieldPhone, supplier.FieldAddress, supplier.FieldRucNit:
			values[i] = new(sql.NullString)
		case supplier.FieldCreatedAt, supplier.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Supplier", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Supplier fields.
func (s *Supplier) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplier.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case supplier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case supplier.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				s.Email = value.String
			}
		case supplier.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				s.Phone = value.String
			}
		case supplier.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				s.Address = value.String
			}
		case supplier.FieldRucNit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ruc_nit", values[i])
			} else if value.Valid {
				s.RucNit = value.String
			}
		case supplier.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				s.TenantID = int(value.Int64)
			}
		case supplier.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case supplier.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryPurchaseInvoices queries the "purchase_invoices" edge of the Supplier entity.
func (s *Supplier) QueryPurchaseInvoices() *PurchaseInvoiceQuery {
	return (&SupplierClient{config: s.config}).QueryPurchaseInvoices(s)
}

// Update returns a builder for updating this Supplier.
// Note that you need to call Supplier.Unwrap() before calling this method if this Supplier
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Supplier) Update() *SupplierUpdateOne {
	return (&SupplierClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Supplier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Supplier) Unwrap() *Supplier {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Supplier is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Supplier) String() string {
	var builder strings.Builder
	builder.WriteString("Supplier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(s.Email)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(s.Phone)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(s.Address)
	builder.WriteString(", ")
	builder.WriteString("ruc_nit=")
	builder.WriteString(s.RucNit)
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", s.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Suppliers is a parsable slice of Supplier.
type Suppliers []*Supplier

func (s Suppliers) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
