// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/supplierpayment"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// SupplierPayment is the model entity for the SupplierPayment schema.
type SupplierPayment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ID de la factura de compra
	PurchaseInvoiceID int `json:"purchase_invoice_id,omitempty"`
	// ID del proveedor
	SupplierID int `json:"supplier_id,omitempty"`
	// Monto del pago
	Amount float64 `json:"amount,omitempty"`
	// Fecha del pago
	PaymentDate time.Time `json:"payment_date,omitempty"`
	// Método de pago (cash, transfer, check, credit_card)
	PaymentMethod string `json:"payment_method,omitempty"`
	// Referencia del pago (número de cheque, transferencia, etc.)
	Reference string `json:"reference,omitempty"`
	// Notas adicionales
	Notes string `json:"notes,omitempty"`
	// ID del tenant
	TenantID int `json:"tenant_id,omitempty"`
	// ID del usuario que registró el pago
	UserID int `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierPayment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplierpayment.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case supplierpayment.FieldID, supplierpayment.FieldPurchaseInvoiceID, supplierpayment.FieldSupplierID, supplierpayment.FieldTenantID, supplierpayment.FieldUserID:
			values[i] = new(sql.NullInt64)
		case supplierpayment.FieldPaymentMethod, supplierpayment.FieldReference, supplierpayment.FieldNotes:
			values[i] = new(sql.NullString)
		case supplierpayment.FieldPaymentDate, supplierpayment.FieldCreatedAt, supplierpayment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type SupplierPayment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierPayment fields.
func (sp *SupplierPayment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplierpayment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sp.ID = int(value.Int64)
		case supplierpayment.FieldPurchaseInvoiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field purchase_invoice_id", values[i])
			} else if value.Valid {
				sp.PurchaseInvoiceID = int(value.Int64)
			}
		case supplierpayment.FieldSupplierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				sp.SupplierID = int(value.Int64)
			}
		case supplierpayment.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				sp.Amount = value.Float64
			}
		case supplierpayment.FieldPaymentDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field payment_date", values[i])
			} else if value.Valid {
				sp.PaymentDate = value.Time
			}
		case supplierpayment.FieldPaymentMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_method", values[i])
			} else if value.Valid {
				sp.PaymentMethod = value.String
			}
		case supplierpayment.FieldReference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reference", values[i])
			} else if value.Valid {
				sp.Reference = value.String
			}
		case supplierpayment.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				sp.Notes = value.String
			}
		case supplierpayment.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				sp.TenantID = int(value.Int64)
			}
		case supplierpayment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				sp.UserID = int(value.Int64)
			}
		case supplierpayment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sp.CreatedAt = value.Time
			}
		case supplierpayment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sp.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this SupplierPayment.
// Note that you need to call SupplierPayment.Unwrap() before calling this method if this SupplierPayment
// was returned from a transaction, and the transaction was committed or rolled back.
func (sp *SupplierPayment) Update() *SupplierPaymentUpdateOne {
	return (&SupplierPaymentClient{config: sp.config}).UpdateOne(sp)
}

// Unwrap unwraps the SupplierPayment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sp *SupplierPayment) Unwrap() *SupplierPayment {
	_tx, ok := sp.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierPayment is not a transactional entity")
	}
	sp.config.driver = _tx.drv
	return sp
}

// String implements the fmt.Stringer.
func (sp *SupplierPayment) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierPayment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sp.ID))
	builder.WriteString("purchase_invoice_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.PurchaseInvoiceID))
	builder.WriteString(", ")
	builder.WriteString("supplier_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.SupplierID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", sp.Amount))
	builder.WriteString(", ")
	builder.WriteString("payment_date=")
	builder.WriteString(sp.PaymentDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("payment_method=")
	builder.WriteString(sp.PaymentMethod)
	builder.WriteString(", ")
	builder.WriteString("reference=")
	builder.WriteString(sp.Reference)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(sp.Notes)
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.TenantID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", sp.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sp.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupplierPayments is a parsable slice of SupplierPayment.
type SupplierPayments []*SupplierPayment

func (sp SupplierPayments) config(cfg config) {
	for _i := range sp {
		sp[_i].config = cfg
	}
}
