// Code generated by ent, DO NOT EDIT.

package ent

import (
	"Veritasbackend/ent/predicate"
	"Veritasbackend/ent/purchaseinvoice"
	"Veritasbackend/ent/supplier"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SupplierUpdate is the builder for updating Supplier entities.
type SupplierUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierMutation
}

// Where appends a list predicates to the SupplierUpdate builder.
func (su *SupplierUpdate) Where(ps ...predicate.Supplier) *SupplierUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetName sets the "name" field.
func (su *SupplierUpdate) SetName(s string) *SupplierUpdate {
	su.mutation.SetName(s)
	return su
}

// SetEmail sets the "email" field.
func (su *SupplierUpdate) SetEmail(s string) *SupplierUpdate {
	su.mutation.SetEmail(s)
	return su
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (su *SupplierUpdate) SetNillableEmail(s *string) *SupplierUpdate {
	if s != nil {
		su.SetEmail(*s)
	}
	return su
}

// ClearEmail clears the value of the "email" field.
func (su *SupplierUpdate) ClearEmail() *SupplierUpdate {
	su.mutation.ClearEmail()
	return su
}

// SetPhone sets the "phone" field.
func (su *SupplierUpdate) SetPhone(s string) *SupplierUpdate {
	su.mutation.SetPhone(s)
	return su
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (su *SupplierUpdate) SetNillablePhone(s *string) *SupplierUpdate {
	if s != nil {
		su.SetPhone(*s)
	}
	return su
}

// ClearPhone clears the value of the "phone" field.
func (su *SupplierUpdate) ClearPhone() *SupplierUpdate {
	su.mutation.ClearPhone()
	return su
}

// SetAddress sets the "address" field.
func (su *SupplierUpdate) SetAddress(s string) *SupplierUpdate {
	su.mutation.SetAddress(s)
	return su
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (su *SupplierUpdate) SetNillableAddress(s *string) *SupplierUpdate {
	if s != nil {
		su.SetAddress(*s)
	}
	return su
}

// ClearAddress clears the value of the "address" field.
func (su *SupplierUpdate) ClearAddress() *SupplierUpdate {
	su.mutation.ClearAddress()
	return su
}

// SetRucNit sets the "ruc_nit" field.
func (su *SupplierUpdate) SetRucNit(s string) *SupplierUpdate {
	su.mutation.SetRucNit(s)
	return su
}

// SetNillableRucNit sets the "ruc_nit" field if the given value is not nil.
func (su *SupplierUpdate) SetNillableRucNit(s *string) *SupplierUpdate {
	if s != nil {
		su.SetRucNit(*s)
	}
	return su
}

// ClearRucNit clears the value of the "ruc_nit" field.
func (su *SupplierUpdate) ClearRucNit() *SupplierUpdate {
	su.mutation.ClearRucNit()
	return su
}

// SetTenantID sets the "tenant_id" field.
func (su *SupplierUpdate) SetTenantID(i int) *SupplierUpdate {
	su.mutation.ResetTenantID()
	su.mutation.SetTenantID(i)
	return su
}

// AddTenantID adds i to the "tenant_id" field.
func (su *SupplierUpdate) AddTenantID(i int) *SupplierUpdate {
	su.mutation.AddTenantID(i)
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SupplierUpdate) SetUpdatedAt(t time.Time) *SupplierUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// AddPurchaseInvoiceIDs adds the "purchase_invoices" edge to the PurchaseInvoice entity by IDs.
func (su *SupplierUpdate) AddPurchaseInvoiceIDs(ids ...int) *SupplierUpdate {
	su.mutation.AddPurchaseInvoiceIDs(ids...)
	return su
}

// AddPurchaseInvoices adds the "purchase_invoices" edges to the PurchaseInvoice entity.
func (su *SupplierUpdate) AddPurchaseInvoices(p ...*PurchaseInvoice) *SupplierUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPurchaseInvoiceIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (su *SupplierUpdate) Mutation() *SupplierMutation {
	return su.mutation
}

// ClearPurchaseInvoices clears all "purchase_invoices" edges to the PurchaseInvoice entity.
func (su *SupplierUpdate) ClearPurchaseInvoices() *SupplierUpdate {
	su.mutation.ClearPurchaseInvoices()
	return su
}

// RemovePurchaseInvoiceIDs removes the "purchase_invoices" edge to PurchaseInvoice entities by IDs.
func (su *SupplierUpdate) RemovePurchaseInvoiceIDs(ids ...int) *SupplierUpdate {
	su.mutation.RemovePurchaseInvoiceIDs(ids...)
	return su
}

// RemovePurchaseInvoices removes "purchase_invoices" edges to PurchaseInvoice entities.
func (su *SupplierUpdate) RemovePurchaseInvoices(p ...*PurchaseInvoice) *SupplierUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePurchaseInvoiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SupplierUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	su.defaults()
	if len(su.hooks) == 0 {
		if err = su.check(); err != nil {
			return 0, err
		}
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SupplierMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = su.check(); err != nil {
				return 0, err
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			if su.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SupplierUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SupplierUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SupplierUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SupplierUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := supplier.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SupplierUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	return nil
}

func (su *SupplierUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   supplier.Table,
			Columns: supplier.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplier.FieldID,
			},
		},
	}
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldName,
		})
	}
	if value, ok := su.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldEmail,
		})
	}
	if su.mutation.EmailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldEmail,
		})
	}
	if value, ok := su.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldPhone,
		})
	}
	if su.mutation.PhoneCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldPhone,
		})
	}
	if value, ok := su.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldAddress,
		})
	}
	if su.mutation.AddressCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldAddress,
		})
	}
	if value, ok := su.mutation.RucNit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldRucNit,
		})
	}
	if su.mutation.RucNitCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldRucNit,
		})
	}
	if value, ok := su.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplier.FieldTenantID,
		})
	}
	if value, ok := su.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplier.FieldTenantID,
		})
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplier.FieldUpdatedAt,
		})
	}
	if su.mutation.PurchaseInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPurchaseInvoicesIDs(); len(nodes) > 0 && !su.mutation.PurchaseInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PurchaseInvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// SupplierUpdateOne is the builder for updating a single Supplier entity.
type SupplierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierMutation
}

// SetName sets the "name" field.
func (suo *SupplierUpdateOne) SetName(s string) *SupplierUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetEmail sets the "email" field.
func (suo *SupplierUpdateOne) SetEmail(s string) *SupplierUpdateOne {
	suo.mutation.SetEmail(s)
	return suo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (suo *SupplierUpdateOne) SetNillableEmail(s *string) *SupplierUpdateOne {
	if s != nil {
		suo.SetEmail(*s)
	}
	return suo
}

// ClearEmail clears the value of the "email" field.
func (suo *SupplierUpdateOne) ClearEmail() *SupplierUpdateOne {
	suo.mutation.ClearEmail()
	return suo
}

// SetPhone sets the "phone" field.
func (suo *SupplierUpdateOne) SetPhone(s string) *SupplierUpdateOne {
	suo.mutation.SetPhone(s)
	return suo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suo *SupplierUpdateOne) SetNillablePhone(s *string) *SupplierUpdateOne {
	if s != nil {
		suo.SetPhone(*s)
	}
	return suo
}

// ClearPhone clears the value of the "phone" field.
func (suo *SupplierUpdateOne) ClearPhone() *SupplierUpdateOne {
	suo.mutation.ClearPhone()
	return suo
}

// SetAddress sets the "address" field.
func (suo *SupplierUpdateOne) SetAddress(s string) *SupplierUpdateOne {
	suo.mutation.SetAddress(s)
	return suo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (suo *SupplierUpdateOne) SetNillableAddress(s *string) *SupplierUpdateOne {
	if s != nil {
		suo.SetAddress(*s)
	}
	return suo
}

// ClearAddress clears the value of the "address" field.
func (suo *SupplierUpdateOne) ClearAddress() *SupplierUpdateOne {
	suo.mutation.ClearAddress()
	return suo
}

// SetRucNit sets the "ruc_nit" field.
func (suo *SupplierUpdateOne) SetRucNit(s string) *SupplierUpdateOne {
	suo.mutation.SetRucNit(s)
	return suo
}

// SetNillableRucNit sets the "ruc_nit" field if the given value is not nil.
func (suo *SupplierUpdateOne) SetNillableRucNit(s *string) *SupplierUpdateOne {
	if s != nil {
		suo.SetRucNit(*s)
	}
	return suo
}

// ClearRucNit clears the value of the "ruc_nit" field.
func (suo *SupplierUpdateOne) ClearRucNit() *SupplierUpdateOne {
	suo.mutation.ClearRucNit()
	return suo
}

// SetTenantID sets the "tenant_id" field.
func (suo *SupplierUpdateOne) SetTenantID(i int) *SupplierUpdateOne {
	suo.mutation.ResetTenantID()
	suo.mutation.SetTenantID(i)
	return suo
}

// AddTenantID adds i to the "tenant_id" field.
func (suo *SupplierUpdateOne) AddTenantID(i int) *SupplierUpdateOne {
	suo.mutation.AddTenantID(i)
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SupplierUpdateOne) SetUpdatedAt(t time.Time) *SupplierUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// AddPurchaseInvoiceIDs adds the "purchase_invoices" edge to the PurchaseInvoice entity by IDs.
func (suo *SupplierUpdateOne) AddPurchaseInvoiceIDs(ids ...int) *SupplierUpdateOne {
	suo.mutation.AddPurchaseInvoiceIDs(ids...)
	return suo
}

// AddPurchaseInvoices adds the "purchase_invoices" edges to the PurchaseInvoice entity.
func (suo *SupplierUpdateOne) AddPurchaseInvoices(p ...*PurchaseInvoice) *SupplierUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPurchaseInvoiceIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (suo *SupplierUpdateOne) Mutation() *SupplierMutation {
	return suo.mutation
}

// ClearPurchaseInvoices clears all "purchase_invoices" edges to the PurchaseInvoice entity.
func (suo *SupplierUpdateOne) ClearPurchaseInvoices() *SupplierUpdateOne {
	suo.mutation.ClearPurchaseInvoices()
	return suo
}

// RemovePurchaseInvoiceIDs removes the "purchase_invoices" edge to PurchaseInvoice entities by IDs.
func (suo *SupplierUpdateOne) RemovePurchaseInvoiceIDs(ids ...int) *SupplierUpdateOne {
	suo.mutation.RemovePurchaseInvoiceIDs(ids...)
	return suo
}

// RemovePurchaseInvoices removes "purchase_invoices" edges to PurchaseInvoice entities.
func (suo *SupplierUpdateOne) RemovePurchaseInvoices(p ...*PurchaseInvoice) *SupplierUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePurchaseInvoiceIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SupplierUpdateOne) Select(field string, fields ...string) *SupplierUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Supplier entity.
func (suo *SupplierUpdateOne) Save(ctx context.Context) (*Supplier, error) {
	var (
		err  error
		node *Supplier
	)
	suo.defaults()
	if len(suo.hooks) == 0 {
		if err = suo.check(); err != nil {
			return nil, err
		}
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SupplierMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = suo.check(); err != nil {
				return nil, err
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			if suo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = suo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, suo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Supplier)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SupplierMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SupplierUpdateOne) SaveX(ctx context.Context) *Supplier {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SupplierUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SupplierUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SupplierUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := supplier.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SupplierUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := supplier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Supplier.name": %w`, err)}
		}
	}
	return nil
}

func (suo *SupplierUpdateOne) sqlSave(ctx context.Context) (_node *Supplier, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   supplier.Table,
			Columns: supplier.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplier.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Supplier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplier.FieldID)
		for _, f := range fields {
			if !supplier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldName,
		})
	}
	if value, ok := suo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldEmail,
		})
	}
	if suo.mutation.EmailCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldEmail,
		})
	}
	if value, ok := suo.mutation.Phone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldPhone,
		})
	}
	if suo.mutation.PhoneCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldPhone,
		})
	}
	if value, ok := suo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldAddress,
		})
	}
	if suo.mutation.AddressCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldAddress,
		})
	}
	if value, ok := suo.mutation.RucNit(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: supplier.FieldRucNit,
		})
	}
	if suo.mutation.RucNitCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: supplier.FieldRucNit,
		})
	}
	if value, ok := suo.mutation.TenantID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplier.FieldTenantID,
		})
	}
	if value, ok := suo.mutation.AddedTenantID(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: supplier.FieldTenantID,
		})
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: supplier.FieldUpdatedAt,
		})
	}
	if suo.mutation.PurchaseInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPurchaseInvoicesIDs(); len(nodes) > 0 && !suo.mutation.PurchaseInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PurchaseInvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   supplier.PurchaseInvoicesTable,
			Columns: []string{supplier.PurchaseInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: purchaseinvoice.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Supplier{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
