// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"time"
)

const (
	// Label holds the string label denoting the supplier type in the database.
	Label = "supplier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldRucNit holds the string denoting the ruc_nit field in the database.
	FieldRucNit = "ruc_nit"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePurchaseInvoices holds the string denoting the purchase_invoices edge name in mutations.
	EdgePurchaseInvoices = "purchase_invoices"
	// Table holds the table name of the supplier in the database.
	Table = "suppliers"
	// PurchaseInvoicesTable is the table that holds the purchase_invoices relation/edge.
	PurchaseInvoicesTable = "purchase_invoices"
	// PurchaseInvoicesInverseTable is the table name for the PurchaseInvoice entity.
	// It exists in this package in order to avoid circular dependency with the "purchaseinvoice" package.
	PurchaseInvoicesInverseTable = "purchase_invoices"
	// PurchaseInvoicesColumn is the table column denoting the purchase_invoices relation/edge.
	PurchaseInvoicesColumn = "supplier_id"
)

// Columns holds all SQL columns for supplier fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldAddress,
	FieldRucNit,
	FieldTenantID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
